### ISSUE TITLE
Discrepancy between EPUB Accessibility Techniques 1.0 and W3 WebSchemas/Accessibility

### ISSUE THREAD

**Issue by nekennedy** [w3c/publ-a11y#1]
From http://www.idpf.org/epub/a11y/techniques/techniques.html#meta-004
Do not skip reporting hazards just because an EPUB Publication does not contain any content that could present risks. Users cannot infer a meaning when no metadata is present. The value "none" can be used in such cases instead of repeating each non-hazard.

From https://www.w3.org/wiki/WebSchemas/Accessibility
All three of the negative properties should be set if none of the hazards are known to exist. If the content has hazard(s), include positive assertions for the hazards it has and negative assertions for the others.

Not sure if this discrepancy is intentional or something we missed.

**Comment by mattgarrish** [comment]
The web schemas wiki needs updating. Notice it doesn't list the "none" value. We agreed to add it while developing the accessibility specification to avoid having to list three instances every time you know there are no hazards.

**Comment by clapierre** [comment]
Madeleine and I are in the process of updating that webSchema wiki but haven’t completely finished this task yet.  It is on my todo list, hope to get that finished soon once I put out a few other fires :)

Thanks
EOM

Charles LaPierre
Technical Lead, DIAGRAM and Born Accessible
E-mail: charlesl@benetech.org<mailto:charlesl@benetech.org>
Twitter: @CLaPierreA11Y
Skype: charles_lapierre
Phone: 650-600-3301



On Oct 20, 2017, at 11:07 AM, Matt Garrish <notifications@github.com<mailto:notifications@github.com>> wrote:


The web schemas wiki needs updating. Notice it doesn't list the "none" value. We agreed to add it while developing the accessibility specification to avoid having to list three instances every time you know there are no hazards.

**Comment by clapierre** [comment]
Madeleine Rothberg and I are in the process of updating that webSchema wiki but haven’t completely finished this task yet.  It is on my todo list, hope to get that finished soon once I put out a few other fires :)

**Comment by nekennedy** [comment]
Fantastic. Will continue implementing "none".

**Comment by clapierre** [comment]
I have updated the wiki specific to accessibilityHazard=None.  Further additions for additional clarification on accessMode, accessModeSufficient, and accessibilitySummary will be forthcoming.

**Comment by GeorgeKerscher** [comment]
too old. If still a problem, resubmit new issue.
