### ISSUE TITLE
Explain in the A11y Guidelines the accessibility summary  may be  the only metadata that is exposed to users.

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#107]
There are many systems that display metadata. There are also discovery tools that may filter on certain metadata fields. It is possible that the Accessibility Summary may be the only thing people see. We need to clarify this in our guideline.

**Comment by murata2makoto** [comment]
But the summary might be inappropriate for the reading system in question.

>Please note that the accessibility summary is written from the perspective of the supplier creating these files and some features and functions will vary depending on the reading system or distributor the end user is operating within.

**Comment by GeorgeKerscher** [comment]
I removed the sentence that the accessibility summary may be the only metadata people see. This undermines the other recommendations about presenting metadata.
