### ISSUE TITLE
[Grouping Accessibility Metadata] accessModeSufficient = visual?

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#145]
This issue is part of the wider work presented in the issue #144 _Proposal for Grouping Accessibility Metadata into Categories_.

Working on a system for grouping accessibility metadata into distinct categories the editors had this question that we repost in this issue so that it can be discussed by the community.

The question is about metadata `accessModeSufficient = visual`: is `accessModeSufficient = visual` relevant to ebooks? All ebooks can be accessed visually, isn't it? Perhaps it is significant for audiobooks, but then it would be clearly exposed that it is an audiobook. If it is the only metadata maybe this flag for telling that the publication is not accessible.

**Comment by MiiaKirsi** [comment]
To expand what Charles commented: how about books that have a lot of meaningful images without alt text descriptions, but that are not specifically picture books, so most of the content can still be accessed as text? 

Or, what I'm trying to grasp here is that is the accessModeSufficient describing the sort of minimum sensory requirement the user needs to have (here: vision) or the way the publication can at least be accessed (as is pointed out in the data sheet, practically all ebooks can be accessed visually)? If first interpretation, then if a book has a lot of images but they all have good alt descriptions, wouldn't accessModeSufficient be just textual?

**Comment by madeleinerothberg** [comment]
Miia, yes, accessModeSufficient is meant to describe the minimum sensory requirement the user needs. And yes, if a book contains images but they are well-described, then you could have accessModeSufficient=textual. A book with important images that are NOT described that also has text (textbook, how-to, art history) would be stuck with accessModeSufficient=visual even though a fair bit of text is offered, if those images are critical content.

**Comment by avneeshsingh** [comment]
Since most relevant accessibility metadata is displayed by the retailer, it is ok to remove accessmode = visual. We can keep it in this spread sheet for completeness purpose. But we can have a comment that we would not use it in the user experience guide.

**Comment by clapierre** [comment]
I don't think so @avneeshsingh if this is a picture book of any kind then there may only be one accessModeSuffiecient entry of "visual" that is important information.  Also there would be only one accessMode of "visual" as well.

If we ever decide to have personas and I select "blind" I would want my search results to avoid showing me any "picture books" as that would be a frustrating experience and behind the scene would filter on not having accessModeSuffienct="visual" be present.
