### ISSUE TITLE
[Grouping Accessibility Metadata] accessibilityFeature = highContrastDisplay?

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#146]
This issue is part of the wider work presented in the issue #144 _Proposal for Grouping Accessibility Metadata into Categories_.

Working on a system for grouping accessibility metadata into distinct categories the editors had this question that we repost in this issue so that it can be discussed by the community.

The question is about metadata `accessibilityFeature = highContrastDisplay`: is the `highContrastDisplay` metadata related to the publication or the reading device?

**Comment by clapierre** [comment]
Unless the book is designed specifically for a low vision user with high contrast Large font, I wouldn't expect to see this.  I could see such books in a RNIB / CNIB / NFB library for example.  But I agree that most books could be made to be HighContrast in the reading system.

**Comment by madeleinerothberg** [comment]
Agree with Charles -- the intent of this term as a book feature is that the book is a fixed but high contrast book. It could be relevant for illustrations within books, too.

This could be clearer in the definition -- note that for Large Print, just below it, we have a clarification that it is not about transformability.

https://www.w3.org/2021/a11y-discov-vocab/latest/#highContrastDisplay

**Comment by gregoriopellegrino** [comment]
As decided in the [February 9 call](https://github.com/w3c/publ-a11y/wiki/Meeting-minutes-of-Publishing-CG-Accessibility-Task-Force#minutes-of-publishing-cg-accessibility-tf-meeting-held-on-february-9-2023-at-1500-utc) I moved high contrast metadata to **Book features** group.
