### ISSUE TITLE
[Grouping Accessibility Metadata] ONIX codelist 196: 25 Use of color?

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#147]
This issue is part of the wider work presented in the issue #144 _Proposal for Grouping Accessibility Metadata into Categories_.

Working on a system for grouping accessibility metadata into distinct categories the editors had this question that we repost in this issue so that it can be discussed by the community.

The question is about metadata ONIX codelist 196: 25 Use of color: does it make sense to group "Use of color" metadata in "Reading Mode: Visual Adjustments" or is it better to move it?

**Comment by gautierchomel** [comment]
For us it's a feature of the book (_the book provides color driven informations_) and there is another way to reach the information (_accessible alternative to the feature_).

I see textbooks that make use of color and will need to have this information.

In a way it refines non visual reading modes but as we can't determine if the feature is present and the equivalent accessible feature is missing we should keep it in features.

**Comment by madeleinerothberg** [comment]
It seems that ONIX and the W3C vocabulary have defined this term as opposites. As Charles notes, the ONIX term means "don't worry, there is an alternative to use of color" whereas Schema/W3C has the term "colorDependent" as a part of the accessMode vocabulary with the definition "Indicates that the resource contains information encoded such that color perception is necessary." If images are accompanied by alternative text, that may remove the barrier. 

The features used to make the color information available to users with color vision deficiencies could be visual or non-visual, and we can't tell from the metadata. It could be that, as Charles describes, all charts use texture/pattern in addition to color, or it could be that there is a text alternative.

I don't know where this leaves us for the metadata grouping, though.

**Comment by avneeshsingh** [comment]
I think we should use a term which is broader than reading mode: visual adjustments. It is possible that a publication is created for one specific user group. It has visual accessibility for that one user group, but do not have facility to make further adjustments.

**Comment by gregoriopellegrino** [comment]
As decided in the [February 9 call](https://github.com/w3c/publ-a11y/wiki/Meeting-minutes-of-Publishing-CG-Accessibility-Task-Force#minutes-of-publishing-cg-accessibility-tf-meeting-held-on-february-9-2023-at-1500-utc) I moved use of color metadata to **Book features** group.
