### ISSUE TITLE
ONIX Certifier Report

### ISSUE THREAD

**Issue by clapierre** [w3c/publ-a11y#15]
The two examples on
https://w3c.github.io/publ-a11y/UX-Guide-Metadata/techniques/onix.html#certifier-report

talk about 94 and 96
what about 95?

196 94	Compliance web page for detailed accessibility information
196 95	Trusted intermediary’s web page for detailed accessibility information
196 96	Publisher’s web page for detailed accessibility information (Publisher Self Certified)

What is the difference between 94 and 95 and shouldn't we explain the difference here since it looks like 95 can also be used.

**Comment by gregoriopellegrino** [comment]
You're right. I think the difference between code 94 and 95 is minimal: it only changes who owns the web page with the accessibility information:

- 94: The web page should be maintained by an independent compliance scheme or testing organization
- 95: The web page should be provided by a trusted intermediary or third party nominated by the publisher

In the first case (94) the report may have been made by a third party organization, even without the publisher's request. In the second case (95) it is the publisher who commissions the audit work from the certifier.

**Comment by avneeshsingh** [comment]
It looks that all of codes 94, 95 and 96 are valid use cases. We can include all three in the ONIX techniques.
