### ISSUE TITLE
[Grouping Accessibility Metadata] accessMode

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#155]
This issue is part of the wider work presented in the issue #144 _Proposal for Grouping Accessibility Metadata into Categories_.

In the grouping we included `accessModeSufficient`, but we missed `accessMode`; I think that needs to be added.

**Comment by gregoriopellegrino** [comment]
I am leaving this comment to keep track, this is not an urgent issue.

In working this issue I realized that for several `accessMode` values it is not super easy to figure out which categories they go into, but also whether they are meaningful to users. I report here for convenience:

- `auditory` in Reading Mode: Audio?
- `chartOnVisual` in Book features or negative in Enable reading without sight?
- `chemOnVisual` in Book features or negative in Enable reading without sight?
- `colorDependent` in Book features
- `diagramOnVisual` in Book features or negative in Enable reading without sight?
- `mathOnVisual` in Book features or negative in Enable reading without sight?
- `musicOnVisual` in Book features or negative in Enable reading without sight?
- `tactile` in Book features or General information (supplement the bibliographic information)?
- `textOnVisual` in Book features or negative in Enable reading without sight?
- `textual` in Enable reading without sight?
- `visual` in Visual Adjustments?

**Comment by HadrienGardeur** [comment]
Based on our experience implementing accessibility metadata, I find it hard to display `accessMode` to users.

**Comment by gregoriopellegrino** [comment]
I think I can close this issue, as we moved on with the draft.
