### ISSUE TITLE
Proposal for rewriting of Enable Reading without Sight (UX guide)

### ISSUE THREAD

**Issue by gautierchomel** [w3c/publ-a11y#171]
Provided as issue for feedback, here is a proposal for the redaction of the Accessibility information related to non visual reading (also [available as draft](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/index.html#enable-reading-without-sight)):

# Non visual reading
A Yes/No/Unknown answer to the question "Can a user reading without sight get a restitution of all contents?".

Indicates that the content of the digital book can be consulted entirely in text, and the other media required for comprehension are described or have a textual alternative. Also means that all content required for comprehension is fully rendered to assistive technologies.

Most digital publications available include their content in digital text and may indicate that they are suitable for non visual reading. Exceptions are publications where some of the content essential to understanding is included only in images, such as graphs, tables or equations presented as images, and publications where the fixed appearance is created by an image on each page instead of actual text.

## Examples
The examples are provided as long and short sentence for flexibility.

### Long sentence:

Text and images alternatives available in computer-generated voice and Braille.

### Short sentence:

Readable without sight.

**Comment by gregoriopellegrino** [comment]
Thank you. That sounds like a great starting point to me.

If I am not mistaken, this group should include both reading with assistive technologies, text-to-speech, and media overlays (issue #148).

Does it seem feasible to keep it all together?

**Comment by GeorgeKerscher** [comment]
During our call on July 6, we thought "supports non-visual reading" was a term that works well. Some other terms we talked about was replacing restitution  with reading with computer generated speech and refreshable braille.

**Comment by avneeshsingh** [comment]
I think this issue has been addressed. If yes @gautierchomel , can you please close this issue.

**Comment by gautierchomel** [comment]
Copy pasting here the final text (can be seen in [draft](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/index.html#enable-reading-without-sight)). 

4.1 Supports nonvisual reading

Indicates whether all content required for comprehension can be consumed in text and therefore is fully available to assistive technologies and reading system text-to-speech functionality.

This field answers whether nonvisual reading is possible, not possible, or unknown.

Digital publications with essential content included in non-textual form (such as graphs, tables or equations presented as images, videos, etc.) must include textual alternatives to ensure that users reading with other senses than sight (mainly auditory and tactile) have access to the same information as visual readers. These textual alternatives can include extended descriptions, transcripts, captions, etc. depending on the nature of the nonvisual content.

4.1.1 Examples

The examples are provided as lists of possible descriptive and compact explanations for flexibility of adoption.
[Example 2](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/index.html#example-descriptive-explanations): Descriptive explanations

    All content available for computer-generated speech and braille reading.
    Portions of the content will not be available in computer-generated speech and braille.
    Portions of the content may not be available in computer-generated speech and braille.

[Example 3](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/index.html#example-compact-explanations): Compact explanations

    Readable in computer-generated audio and braille.
    Not fully readable in computer-generated audio and braille.
    May not be fully readable in computer-generated audio and braille.
