### ISSUE TITLE
ONIX add note

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#18]
Feedback from EditEUR.

https://w3c.github.io/publ-a11y/UX-Guide-Metadata/techniques/onix.html

For this page suggested new note: 

# NOTE (add note)
ONIX messages describe products for the global book supply chain and will be sent from publisher or creator of the epub or digital audiobook to those who will make the products available for sale, lending or subscription. These platforms may not yet have the actual files, as they may not yet be ready, or may only choose to list them for sale if they have certain accessibility features.  ONIX also only describes a product, it cannot describe the features of the reading systems on which a product may be accessed. It is important to use ONIX metadata as a complement to the accessibility data embedded within the publication itself, if describing accessible books, audiobooks and related products for the global book supply chain.
An ONIX file can be used to display accessibility information in advance of publication or when you do not have access to the metadata in the digital file itself. Some accessibility information may only be available when you have access to the file itself.
If you are unfamiliar with ONIX, then there is more documentation available from EDItEUR.org.

**Comment by madeleinerothberg** [comment]
I support adding this note. Perhaps we should add a link to the Application Note on accessibility at:
https://www.editeur.org/files/ONIX%203/APPNOTE%20Accessibility%20metadata%20in%20ONIX.pdf

**Comment by madeleinerothberg** [comment]
Actually, for robustness, we may wish to link to the landing page for Application Notes:
https://www.editeur.org/93/Release-3.0-Downloads/#How%20to
