### ISSUE TITLE
Have 3rd Party Certification on Main Accessibility Page

### ISSUE THREAD

**Issue by clapierre** [w3c/publ-a11y#181]
For content that has gone under a stringent certification review process having this information displayed on the initial Accessibility Page is important to promote the discover of certified accessible material, instead of having this information buried in the "additional accessibility information".

3rd party certification like LIA and Benetech's GCA (Global Certified Accessible) program have been around for years and is a recognized and trusted to ensure accessibility.

In the section of Conformance if the title has a certifierCredential either the textual information or if applicable an image (logo/stamp) with alt text description of the certification be presented to the user in this section.

**Comment by avneeshsingh** [comment]
In August 24, 2023 meeting, the group resolved to keep 3rd party certifier information in the main accessibility metadata instead of placing it in additional metadata.

**Comment by gautierchomel** [comment]
Addressed, see [Example 13 in November draft](https://rawcdn.githack.com/w3c/publ-a11y/f7f9921cde19fd819683e9ea420482577f84088f/UX-Guide-Metadata/draft/principles/index.html#example-conformance-statements-that-meets-accepted-accessibility-standards-followed-by-detailed-conformance-information): Conformance statements that meets accepted accessibility standards followed by detailed conformance information
