### ISSUE TITLE
What to display in case of absence of metadata

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#184]
Working on the draft of the [User Experience Guide for Displaying Accessibility Metadata](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/?updated#order-of-key-information) we found out that there are cases where the metadata for certain pieces of information may not be available. We need to establish a consistent approach for handling the display of each key information when metadata is absent.

We are seeking community input and consensus on how to handle the situation when metadata is missing for specific key information elements. The main questions for each Key Information we need to address are:

- Should we display key information even when metadata is not present?
- If we decide to display key information in the absence of metadata, what information should be shown?

Key information to address are:
- Supports nonvisual reading
- Pre-recorded audio
- Visual adjustments
- Navigation
- Charts, diagrams, and formulas
- Hazards
- Conformance
- Accessibility summary
- Additional accessibility information

**Comment by gautierchomel** [comment]
From the editor's call we think that the important ones are:

* Supports nonvisual reading
* Visual adjustments
* Conformance

and find it would be valuable to provide flexible compact / descriptive examples.

**Comment by dazrand** [comment]
For consistency we should display the key information, even when not reported.  

I agree with Gautier, those three are a good primary listing which covers most areas. 

When any key items are not reported, either via ONIX of the ebook metadata, I would suggest "Not reported" to indicate it is the failure of the publisher to report status.

**Comment by avneeshsingh** [comment]
[In October 12, 2023 meeting](https://github.com/w3c/publ-a11y/wiki/Minutes-of-Publishing-CG-Accessibility-Task-Force-Meetings) we confirmed that support non-visual reading, visual adjustments and conformance will explicitly state that no information is provided, if these pieces are missing in the metadata.

**Comment by rickj** [comment]
We have decided to not make a declarative statement that things are missing, but acknowledge that they 'may' be included, and they should contact the publisher for clarity.

If we do not detect any a11y metadata fields, we display:
> The publisher of this title has not provided any details on the accessibility features that may be included. You should contact them for more information.
