### ISSUE TITLE
Review the ARIA in HTML document

### ISSUE THREAD

**Issue by rdeltour** [w3c/publ-a11y#2]
The [ARIA in HTML](https://www.w3.org/TR/html-aria/) spec defines (among other things) document conformance requirements for use of ARIA attributes in HTML, which are normative author-level rules. 

The "rules of ARIA attributes usage by HTML language features" table provides normative requirements notably on where DPUB ARIA roles are allowed.

We’re too late for the [CFC for moving to CR](https://github.com/w3c/html-aria/issues/92), but I believe the Publishing Working Group A11y TF should do a group review.

I already opened some issues ([#99](https://github.com/w3c/html-aria/issues/99), [#100](https://github.com/w3c/html-aria/issues/100), [#101](https://github.com/w3c/html-aria/issues/101)), but these should be reviewed by our TF.

cc @TzviyaSiegman, @mattgarrish, @avneeshsingh

**Comment by GeorgeKerscher** [comment]
Too old. If still a problem, please submit a new issue.
