### ISSUE TITLE
Version clarity

### ISSUE THREAD

**Issue by rickj** [w3c/publ-a11y#200]
Given that we have a 1.0 version of:

- the [User Experience Guide for Displaying Accessibility Metadata 1.0](https://www.w3.org/2021/09/UX-Guide-metadata-1.0/principles/)
- the [Display Techniques for EPUB Accessibility Metadata 1.0](https://www.w3.org/publishing/a11y/UX-Guide-metadata/techniques/epub-metadata/)
- the [Display Techniques for ONIX Accessibility Metadata 1.0](https://www.w3.org/publishing/a11y/UX-Guide-metadata/techniques/onix-metadata/)

and work on 1.1 versions of all of these is underway, is there objection to me creating a pull request to update the titles of the in process 1.1 drafts to reflect 1.1 in their titles?

**Comment by GeorgeKerscher** [comment]
No objection by me.

**Comment by rickj** [comment]
Done

**Comment by rickj** [comment]
Pull requests made for all 3 drafts
