### ISSUE TITLE
ONIX Audiobook

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#21]
From EditEUR's feedback:

# Audiobook
Values: Yes / (if No - Omit this section)
This technique relates to Audiobook principle.
This information can be retrieved from ONIX code list 81; Code: 01: Audiobook. ‘
**Can also be retrieved from ProductForm AJ, AN, AO – Digital audio books. – probably more common and reliable than list 81.**
(xpaths for these)
/ONIXMessage/Product/DescriptiveDetail/ProductForm[. eq ‘AJ‘]
/ONIXMessage/Product/DescriptiveDetail/ProductForm[. eq ‘AN‘]
/ONIXMessage/Product/DescriptiveDetail/ProductForm[. eq ‘AO‘]

**Comment by avneeshsingh** [comment]
List 81 is specifically for product content, and code 01 for audio books fits well with our requirements. 
List 150, codes AJ, AN and AO further describe whether the audio file is for download, online streaming etc.

My understanding is that we can stick to list 81, code 01 for audio books content. Publishers may provide code AJ, AN and AO as additional information.
