### ISSUE TITLE
Hazards

### ISSUE THREAD

**Issue by clapierre** [w3c/publ-a11y#222]
For the Hazards section, we wanted to get everyone's opinion on how items should be displayed depending on if there are no hazards "none" , vs. "unknown" hazards or unknown hazards because the author has no metadata for hazards listed.

Here a suggestion, but feel free to discuss other options.

**NOTE**
This key information can be hidden if it is known that there are no accessibility hazards.

Identifies any potential hazards (e.g., flashing elements, background sounds, and motion simulation) that could afflict physiologically sensitive users.

Unlike other accessibility properties, the presence of hazards can be expressed either positively or negatively. This is because users search for content that is safe for them as well as want to know when content is potentially dangerous to them.

When this metadata is missing or specifically marked as 'Unknown' this group should always be displayed. Indicate that no metadata is provided if that is the case, or the metadata specifically states 'Unknown' Hazards exist.

**Unknown Cases:**

accessibilityHazard='unknown'
or
missing accessibilityHazard in the provided metadata

Result: Always display Hazards = Unknown, or "The author has not provided any hazard information."

**No Hazard Cases**

accessibilityHazard='none'
or
accessibilityHazard='noFlashingHazard' 
accessibilityHazard='noMotionSimulationHazard' 
accessibilityHazard='noSoundHazard' 

Result: May say Hazards = none, or specify each no Flashing, no Motion Simulation, and no Sound Hazards
Or 
Do not display anything as this will be the case for 99%+ of the EPUBs

In the case where there is some kind of hazard then this information must be displayed
e.g.. Hazard = Flashing

**Comment by rickj** [comment]
While I see the value of your proposal, is it the rule we want to follow for any of the other key information sections?  I think being consistent across those is important, and I see substantial issues with trying to have an effective message in the absence of any metadata for many of them.

Given the above, I would hesitate to implement this.  The absence of any 'claim' in any of the key accessibility areas is, in an of itself, a 'claim' the publisher is making.  Failure to state something contributes as much to the validity of claims as explicitly making one.

**Comment by GeorgeKerscher** [comment]
Rick, you are saying that hazard information must always be displayed, right?

So, if there are hazards, they would be listed, if there are none, then this is stated, and if the status is unknown or not reported, it would be unknown.

**Comment by gautierchomel** [comment]
Users feedback and previous discussions stated that this choice would be related to the collections and public addressed by the platform. Having a hundred of thousands textuals eBooks displaying "no hazard" would not be pertinent. Instead, as actually indicated in the Filtering section:

> Platforms dedicated to selling children's books and interactive content may want to allow users to select books with no hazards, ... 

Also to note that users feedback showed expecting _violence rated_ or _minimum age_ information thru the Hazard wording.

**Comment by gautierchomel** [comment]
We have a nice wording for the Filtering section, but we may be missing a similar statement for displaying. see #252
