### ISSUE TITLE
Acknowledgement Section Questions

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#224]
The Acknowledgements section has three parts right now: Acknowledgements, Contributors  and Reviewers. Do we want to keep this approach or just have an Acknowledgements section?

Also, do we want to include the people referenced in version 1 of the User Experience or only the people who participated in this version.

I was thinking of  only having a single Acknowledgements section and having people who contributed to this version. What do others think?

**Comment by rickj** [comment]
Have we had anyone participate in only one role?  It seems to me that anyone who has contributed has also reviewed, and the reverse that reviewers have also contributed.  That leaves Acknowledgements... who would we acknowledge that had not contributed or reviewed?

Given the above, I'm in favor of your suggestion to only have acknowledgements.

The 1.0 version is canonical and lists those involved for anyone needing that reference.  The 2.0 version should have people involved in that version, in my opinion, so I also agree with you there.

**Comment by GeorgeKerscher** [comment]
We updated the acknowledgements section and merged it.
