### ISSUE TITLE
ONIX Hazards

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#23]
From EditEUR's feedback:

# Hazards
Values: flashing, motion simulation, sound, no flashing, no motion simulation, no sound, none, or Unknown.

This technique relates to Hazards principle.

<del>Not available in ONIX</del>
**ONIX uses a composite to indicate different hazards 
<ProductFormFeatureType>12</ProductFormFeatureType> (12 means it is a hazard warning)
<ProductFormFeatureValue>xx</ProductFormFeatureValue> a value from list 143 to indicate the nature of a hazard or the fact that a product has been checked and does not have that particular hazard.**

**Comment by avneeshsingh** [comment]
Yes code list 143, codes 13 to 18 take care of the three main hazards that are there in values of schema.org properties.
