### ISSUE TITLE
What are the needs for who's in charge of setting up accessibility metadatas?

### ISSUE THREAD

**Issue by gautierchomel** [w3c/publ-a11y#234]
During the work on rewriting the [User Experience Guide for Displaying Accessibility Metadata 2.0](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/?updated), the question raised often of this document as guidance for publishers to know how their metadata will be used.

From the feedback collected on the first version of this document, we think that this document must keep the scope of serving users' needs. Aside from that, the attached techniques are to serve the implementers' needs. 

This issue is to collect the needs related to setting up accessibility metadata and help determine how complementary information or documents could provide context and guidance for people responsible for producing, filling in or improving metadata for distributors, reference organisations and bibliographic agencies

**Comment by gautierchomel** [comment]
As an additional asset generated by the project [Signposting accessible digital books](https://edition-accessible.github.io/signalement/en/index-en.html) in the France French context, we reused some of the created material as a [Metadata Dictionary (in French)](https://www.lina25.fr/ressources/metadonnes). 

It has been used by distributors to set up conditional forms to guide the person adding a file to the distribution system to give the correct information (the form generates the metadata). 

The [Metadata Dictionary source code is available from GitHub](https://github.com/edition-accessible/lina25/blob/main/ressources/metadonnes.md) under a free licence and can be reused.

**Comment by GeorgeKerscher** [comment]
I believe we have addressed the items in this issue. We have added sections about the "Claims" by the publisher and that the distributer is only providing the publisher's metadata.

If this is incorrect, please open a new issue and describe the problem in light of the latest version of the, Accessibility Metadata Display Guide for Digital Publications 2.0
