### ISSUE TITLE
Add intros to display techniques

### ISSUE THREAD

**Issue by mattgarrish** [w3c/publ-a11y#25]
It's not easy to understand the display documents in context unless you start from the UX guide. There are only notes in the first metadata section of each document that reference back to the UX guide, but otherwise they jump right into explaining the techniques.

It would make the documents easier to understand for people who may find them first if there were separate introductions that set up the purpose of these documents and explained their relationship with the UX guide.

**Comment by gregoriopellegrino** [comment]
At the moment in the techniques docs we have:

> General principles on how to display accessibility metadata for EPUB are in the **User Experience Guide for Displaying Accessibility Metadata**

Can you all help me write down it better?

My proposal is:

> This document provides guidance for developers on meeting **User Experience Guide for Displaying Accessibility Metadata**. These are some practical examples of how to extract information and show it to end users.

**Comment by avneeshsingh** [comment]
Looks good Gregorio . Following is slightly updated version:

This document provides techniques for meeting the guidelines of User Experience Guide for Displaying Accessibility Metadata. It provides practical examples for extracting information from the machine readable ONIX metadata for showing it to the end users.

For EPUB accessibility metadata techniques, ONIX can be replaced.
