### ISSUE TITLE
Principles document examples for nonvisual reading

### ISSUE THREAD

**Issue by madeleinerothberg** [w3c/publ-a11y#251]
In the Principles document Section 3.1 Supports nonvisual reading the Examples are as follows:

[EXAMPLE 1](https://rawcdn.githack.com/w3c/publ-a11y/f7f9921cde19fd819683e9ea420482577f84088f/UX-Guide-Metadata/draft/principles/index.html#example-descriptive-explanations): Descriptive explanations
All content is available for reading using computer-generated speech and refreshable braille .
Portions of the content may not be available for reading using computer-generated speech and refreshable braille.
Portions of the content are not available for reading using computer-generated speech and refreshable braille.
[EXAMPLE 2](https://rawcdn.githack.com/w3c/publ-a11y/f7f9921cde19fd819683e9ea420482577f84088f/UX-Guide-Metadata/draft/principles/index.html#example-compact-explanations): Compact explanations
Readable in computer-generated audio and braille.
Not fully readable in computer-generated audio and braille.
May not be fully readable in computer-generated audio and braille.
Unknown.

Are these intended to be parallel in the order they are listed, with each compact explanation matching a descriptive explanation? Maybe items 2 and 3 of the compact versions should be swapped? And there is no descriptive version for unknown.

**Comment by GeorgeKerscher** [comment]
Yes, the order in the compact need to be swaped.

However the unknown with a descriptive triggers another question. I will file a new issue on that.

**Comment by GeorgeKerscher** [comment]
I believe this is  fixed in the current version of Principles. Currently we do not have an unknown.

Best
George

**Comment by avneeshsingh** [comment]
@madeleinerothberg , can you please verify if it is fixed.

**Comment by madeleinerothberg** [comment]
The order is now consistent. There are some spaces missing in the  4th bullet in each section (not known) but we are still trying to decide if we want an "unknown" bullet at all.

**Comment by GeorgeKerscher** [comment]
Is the order consistent in the Principles and in both techniques for non-visual? I thought the second and third are reversed between the principles and the techniques. Please double check.

Still agree that we do not know about unknown.

**Comment by madeleinerothberg** [comment]
This ticket is only about the Principles document and the order of the descriptive and compact examples which now match. I think this can be closed.

We talked on the editors call on 4/11 about whether the order in Principles should match the order in the technical instructions in the Techniques docs, which rely on the order that works best for the if/else statements. That is [issue #260 ](https://github.com/w3c/publ-a11y/issues/260)which you opened recently.
