### ISSUE TITLE
Principles and unknown

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#262]
Based on notes from April 25, 2024, I reviewed the principles forproblems related to display of unknown. I have several questions.

First, in the first three there is the note that says: This key information should always be displayed, even if there is no metadata (with the relevant wording).

"Relevant wording" seems to be a problem. Should we be more specific? Should we reference the unknown compact or descriptive statement?

Second,  in theconformance section,the third example states that the conformance is unknown, because the publisher is not required to provide it. However, we do not have an example where the information is missing because the publisher just did not provide it. Should we modify the third example or create another example? We could add a paragraph to the details of the third one that says, that the conformance metadata is missing.

Third, it is not clear to me where we should state that the order of the compact or descriptive statements may not be in the same order as in the techniques. Should we make this statement once in the Principles or in each of the Techniques? It might not needed to be added at all, because only one statement is presented to the end user.
The hazards section does mention unknown, and the others do not have unknown statements; only the first three and the hazard has unknown. So, I think we are good. Of course, the hazard section will need to be reviewed.
Once I have guidance, I can modify the Principles.

**Comment by clapierre** [comment]
> First, in the first three there is the note that says: This key information should always be displayed, even if there is no metadata (with the relevant wording).
> 
> "Relevant wording" seems to be a problem. Should we be more specific? Should we reference the unknown compact or descriptive statement?
> 

I think you are right George, the Note "This key information should always be displayed, even if there is no metadata (with the relevant wording)." should probably say in the ()'s something like 

This key information should always be displayed, even if there is no metadata, (see examples where this key metadata is missing or unknown.)

**Comment by clapierre** [comment]
> Second, in the conformance section, the third example states that the conformance is unknown, because the publisher is not required to provide it. However, we do not have an example where the information is missing because the publisher just did not provide it. Should we modify the third example or create another example? We could add a paragraph to the details of the third one that says, that the conformance metadata is missing.

I agree George, we need to have a detailed example where the author hasn't put anything in for conformance.  I think adding another paragraph with this would be important to have.

**Comment by clapierre** [comment]
> Third, it is not clear to me where we should state that the order of the compact or descriptive statements may not be in the same order as in the techniques. Should we make this statement once in the Principles or in each of the Techniques? It might not needed to be added at all, because only one statement is presented to the end user

I am not sure after looking this over if this is really necessary. Those looking at the techniques will understand why the order is slightly different than what is in the principals document.  I think we can leave this out for now.

**Comment by clapierre** [comment]
Example 5 detailed is missing the certifier and potentially the certifiers credential.

Shouldn't we have a "Self-certified or a certification without a credential" example where there is no credential and one where this is present?
Maybe a separate example for a Self-certified (compact / detailed.

**Comment by madeleinerothberg** [comment]
I agree with @clapierre in response to notes from @GeorgeKerscher. I don't have the background to comment on the certifier issues.

**Comment by GeorgeKerscher** [comment]
PR unknown262 resolves this issue.
