### ISSUE TITLE
Additional accessibility information - level of detail in Display Techniques

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#269]
In 3.3.9 Additional accessibility information of the User Experience Guide for Displaying Accessibility Metadata 2.0 

Structure
For information on any structuring aids that facilitate use of a resource (e.g., annotations, ARIA).

Do we want to include Annotations and is there a clearer definition of annotations?

To include other forms of navigation not specifically referenced in the Navigation section of the display guidelines?

Adaptation
For information on provisions in the content that enable reading in alternative access modes (e.g., closed captions, ruby annotations, sign language, transcript).

For adaptions for Ruby - do we create a separate section that corresponds to the   Internationalization Terms section 4.2.7 of the Schema.org Accessibility Properties for Discoverability Vocabulary ? 
Do we include some of the other terms? EDItEUR has not yet added ONIX codes for these as we are waiting to know if they are needed and will be used?

Tactile
For information on content that is available in tactile form (e.g., tactile content, tactile graphic, tactile objects).

How much Tactile content is being seen in the supply chain ? EDItEUR has not yet added ONIX codes for these as we are waiting to know if they are needed and will be used? So what guidance do we want to include in the document?

Other
For information that does not fall into one of the preceding categories (e.g., timing control and color dependent).

How much extra advice do we include here?  Should we try and have mention for all the values that could be found in Schema or ONIX and therefore may need to be displayed?

**Comment by avneeshsingh** [comment]
Section 3.9 additional accessibility metadata contains the items that the group felt are not widely used or are less important.
All the important accessibility metadata are already listed in section 3.1 to 3.8. If the group realizes that we need to elevate a metadata from additional metadata section to a separate heading, then we can do so.

It is possible that some accessibility metadata in this list may be very important for a niche market, but are not used outside the niche. To address this, I think we should provide a note or explanation that if any of these metadata items are important for your segment of market, then you can elevate it into its own heading/category in your implementation.

**Comment by chrisONIX** [comment]
For Structure - annotations - 
I suggest this is taken out of the Principles document - as this is not useful to accessibility and we do not include it in the techniques document

An Annotated edition can be expressed in ONIX (list 21) - but this is for the whole supply chain and NOT specific to accessibility

**Comment by chrisONIX** [comment]
For the Structure section of additional  metadata there are four types of navigation that exist in ONIX that we can reference:

Single logical reading order
Landmark navigation 
Page list navigation (new value in ONIX)
ARIA roles 

Do we agree these are the four things that should be referenced under Structure in the additional metadata section?

**Comment by chrisONIX** [comment]
For the Adaptation section these are the proposed additional metadata elements that can be listed in the display techniques.
Text-to-speech hinting provided (list 196 - code 21)
Language tagging provided (list 196 - code 22)

For audio content only - a Full transcript is provided - List 175 - code V212 - new code

For video content - It has closed captions - list 175 - code V210 
It has Open captions - list 175 - code V211.
It has Sign language interpretation - List 175 - code V213 - new code


Do we agree these are the values that should be referenced under the Adaption section of Additional metadata ?

**Comment by GeorgeKerscher** [comment]
In the principles the word "annotation" is associated with ARIA and with Ruby. These are not annotations as in the Annotated Alice, which is content.

This in my mind is additional markup that improves the quality of the content.

We have:
For information on any structuring aids that facilitate use of a resource (e.g., annotations, ARIA).
could be changed to:
For information on any structuring aids that facilitate use of a resource (e.g.,  ARIA).

We also have:
closed captions, ruby annotations, sign language, transcript).
could become:
closed captions, ruby markup, sign language, transcript)..

Thoughts?

**Comment by gregoriopellegrino** [comment]
> Page list navigation (new value in ONIX)- list 196 - code 41)

A short comment: "Page list navigation" is present in the navigation techniques.

**Comment by chrisONIX** [comment]
Yes - remove Page list navigation from Structure as already in Navigation

**Comment by chrisONIX** [comment]
For the Clarity section of additional metadata the principles document currently says this:

Clarity - For information on ways that the content has been enhanced for improved auditory or visual clarity (e.g., high contrast display).

These are the values that can be referenced in the ONIX display techniques if agreed: 

ONIX code list 196 - code 24 - Dyslexia readability
ONIX code list 196 - code 25 - Use of color is not sole means of conveying information
ONIX code list 196 - code 26 - Use of high contrast between text and background color
ONIX code list 196 - code 37 - Use of ultra-high contrast between text foreground and background
ONIX code list 196 - code 27 - Use of high contrast between foreground and background audio
ONIX code list 196 - code 28 - Full alternative audio descriptions
ONIX code list 196 - code 38 - Unusual words or abbreviations explained
ONIX code list 196 - code 40 -  Link purposes clear
ONIX code list 175 - code A312 - Without background sounds
ONIX code list 175 - code E205 - Visible page numbering

ONIX code list 21 - code ETR - Easy-to-read edition
ONIX code list 21 - code HRE - High Readability edition
ONIX code list 21 - code LTE - Large Type / Large Print edition
ONIX code list 21 - code ULP - Ultra Large Print Edition


Which of these needs to be added to the Techniques for display ONIX document under additional metadata for clarity?

**Comment by chrisONIX** [comment]
For the Tactile  section of additional metadata the principles document currently says this:
Tactile
For information on content that is available in tactile form (e.g., tactile content, tactile graphic, tactile objects).

These are the values that can be referenced in the ONIX display techniques if agreed:

ONIX code list 21 - code BRL - Braille edition
ONIX code list 175 - code E146 -  BRF - (Braille-ready file) Electronic Braille file

There are no values yet in ONIX code list 81 to Tactile content - this can be added if there is a requirement for these in the book supply chain.
This could be a code for links to tactile content as appropriate but as these are not yet in ONIX , the Tactile section could only reference the two codes above in the ONIX display techniques.

Other possible Braille codes are
ONIX code list 121 - code Brai - this means the content uses Braille as a script 
ONIX code list 175 - various codes for Braille - but these apply more to physical content so not necessary in the display techniques document?

**Comment by chrisONIX** [comment]
For the Content section of additional metadata the principles document currently says this:

Content
For information on specific types of content present in the digital publication (e.g., text on visual, music on visual).

**text on visual** this is already referenced in supports non visual reading. 

There are many values in ONIX code list 81 that could be referenced here but in the ONIX display techniques it may be better to reference some more important ones and then give advice to look for any other code from list 81.

The full list is here:
https://ns.editeur.org/onix/en/81

Suggested values to be included in the ONIX display techniques 
ONIX code list 81 - code 11 - Musical notation
ONIX code list 81 - code 45 - text within image
ONIX code list 81 - code 46 - decorative images or graphics
ONIX code list 81 - code 42 - assessment material 
ONIX code list 81 - code 05 - Game / puzzle
ONIX code list 81 - code 34 - Blank pages or spaces
ONIX code list 81 - code 40 - Scripting
ONIX code list 81 - code 34 - Scripted pop-ups
ONIX code list 81 - code 44 - Sequential art

**Comment by chrisONIX** [comment]
For the Other  section of additional metadata the principles document currently says this:
Other
For information that does not fall into one of the preceding categories (e.g., timing control and color dependent).

ONIX code list 196 - code 25 - Use of color is not sole means of conveying information - has been proposed for the clarity section - do we agree that it should be there or here in the other section?

ONIX values that could be included in the other section.

ONIX code list 196 - code 31 - Accessible controls provided
ONIX code list 196 - code 39 - Supplementary material to an audiobook is accessible
ONIX code list 144 - all codes -  Use of DRM or not ? Should this be displayed if there is a DRM on the product?
ONIX code list 198 - code 01 - Accessibility request contact - should the contact be displayed for accessibility information ?

**Comment by avneeshsingh** [comment]
The issue was discussed in May 23, 2024 meeting.

gpellegrino: in this section this is a catchall for all metadata not previously represented. Chris is starting this work to find what is missing.
… question is: How much we want to go into detail. How much is this metadata used in publishing? should we substructure this section or just list them?
… Chris proposed some structure

gpellegrino: would be nice to know about tactile Graphic, TactileObject etc. since meaningful metadata should be present in the other sections.

Charles: the new EBraille format for braille format will be using that metadata.

AvneeshSingh: EBraille will be used by libraries serving people with print disabilities, at least for now.

gautierchomel: we should not over engineer this, but we have to keep in mind more specific info will be needed. France National Library to have all the born accessible EBooks and collection for copyright exemption. There will be need to extend this work. Stick to what is on the display guide with short list of additional metadata.
… not specific to a specialized collection.

Avneesh: could be a huge list if we keep everything that is in ONIX
… could add a few examples for each section, not the entire list.

George: some of the ONIX codes are embossed braille / paper Braille. Should we put a note in the principals that some additional metadata described below are libraries serving people with alternative content and those context but don't expect to be used in mainstream distribution?

Avneesh: proposed a generic note if there is metadata is needed for your specific audience then you can add this, but it would be up to the implementer to determine what is important for their customers.

gpellegrino: not for special edition and not for paper books, we need to keep this in mind. I think we already wrote something in the introduction, so it should not be needed in the additional metadata section

Avneesh: we can provide updates in this Issue since Chris is not in the call. to keep it simple and let the implementers figure out what is needed for their audiences.

**Comment by GeorgeKerscher** [comment]
We have reworked the additional information extensively. I think this can be closed. If people ask specific questions  about additional information, we should create a new issue.

**Comment by chrisONIX** [comment]
Closed this issue and any individual issue will be created as a new issue
