### ISSUE TITLE
Order of Key Information

### ISSUE THREAD

**Issue by murata2makoto** [w3c/publ-a11y#27]
Section 4 of ["User Experience Guide for Displaying Accessibility Metadata"](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/principles/#techniques) is "Order of Key Information".

The Technical Committee of the Japan DAISY Consortium plans to introduce three sets of accessibility metadata (ruby, horizontal/vertical writing, and ruby).  I suppose that nothing in this draft community group report presents the addition of these sets, but I just want to check.

**Comment by gregoriopellegrino** [comment]
Dear Makoto,
at the moment the new metadata sets are not in the documents. Have they been approved yet?

So in their current state they would fall under "All Accessibility Metadata". That being said, I don't see a problem with adding them.

**Comment by murata2makoto** [comment]
@gregoriopellegrino 

No, not yet approved.  We will soon submit proposals.
