### ISSUE TITLE
is there a double negative in ONIX  pre recorded audio

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#273]
In the pre recorded audio section of the ONIX it says:
Otherwise, if false, it means that none of the metadata is not present.

This phrase is repeated several times. Do we mean:
Otherwise, if false, it means that none of the metadata is present.

I just removed the word not.

**Comment by mattgarrish** [comment]
When you say none of the metadata, it sounds like some of metadata being present is a possibility. If the metadata is either present or not, I'd probably make it "it means that the metadata is not present."

If it's possible that only some is present, then you might want to say: "it means that the metadata is not present or is incomplete."

**Comment by clapierre** [comment]
I think I like Matt's option of "it means that the metadata is not present or is incomplete." @gregoriopellegrino I believe you may need to make changes to that section in the ONIX file.

**Comment by clapierre** [comment]
I will make changes to the EPUB Technique.

**Comment by clapierre** [comment]
I believe this only affects the ONIX version, as the EPUB technique says the following for the ELSE clause:

No information about pre-recorded audio. This key information can be hidden if metadata is missing.

**Comment by gregoriopellegrino** [comment]
These are variables that have value true if at least one of the metadata listed is present, have value false if none of the metadata is present.

I would therefore write like this: "Otherwise, if false, it means that none of the above metadata is present."
