### ISSUE TITLE
ONIX techniques - 4.6 Charts, diagrams, and formulas 

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#277]
In section 4.6.2 Variables setup - we reference:

LET chemical_formula_as_mathml be the result of calling [check for node](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/techniques/onix-metadata/index.html#check-for-node) on onix, /ONIXMessage/Product/DescriptiveDetail/ProductFormFeature[ProductFormFeatureType = "09" and ProductFormFeatureValue = "34"].

However we do not mention. this in section 4.6.1 Understanding the variables - should we add this ?
chemical_formula_as_mathml
If true it indicates that the [code 34 of codelist 196](https://ns.editeur.org/onix/en/196/34) (Accessible chemistry content as MathML) is present in the ONIX record, otherwise if false it means that the metadata is not present.

This means that there is a positive indication that the chemical formulae are presented using MathML and works with compatible assistive technology.

**Comment by GeorgeKerscher** [comment]
I did not see this until now. Yes, Yes, we should be taking advantage of Chemistry in MathML.
