### ISSUE TITLE
Charts and Graphs ONIX metadata

### ISSUE THREAD

**Issue by clapierre** [w3c/publ-a11y#283]
I am concerned that ONIX technique's instructions for Chart's and Graphs is slightly incorrect.

If there are No chart's and graphs in the EPUB but there are Images with Long descriptions or alt text

You will get displayed "Charts and diagrams have extended descriptions" OR "Visualised data also available as non-graphical data"

We should also change the spelling to be "Visualized" with a z

I would think that we should add

IF contains_charts_diagrams AND charts_diagrams_diagrams_as_long_text
 ...
IF contains_charts_diagrams AND charts_diagrams_as_non_graphical_data
...

**Comment by GeorgeKerscher** [comment]
I commented on Charles PR on this topic in the EPUB Accessibility techniques.

Essentially, when Chem on Visual is present, there are three ways to make it accessible:

ChemML is already identified, but we do not know if it works.
Long descriptsions could be used.
There is now Chemistry in MathML.

There is the Chemistry on the Web and in Publishing we might turn to for guidance.

**Comment by gautierchomel** [comment]
> IF contains_charts_diagrams AND charts_diagrams_diagrams_as_long_text
> IF contains_charts_diagrams AND charts_diagrams_as_non_graphical_data

Where should we add that?

**Comment by gautierchomel** [comment]
> We should also change the spelling to be "Visualized" with a z

Shouldn't we then define lang="en-US" xml:lang="en-US"?

**Comment by GeorgeKerscher** [comment]
I copied the whole of the principles and copied it into Word and did a spell and grammar check. I think there are about a dozen suggested changes I should make. Also, I see that the Ruby specification calls it Ruby markup, not Ruby annotations, so that should change as well.  This would mean a lot of changes sprinkled throughout the document.

**Comment by clapierre** [comment]
> > IF contains_charts_diagrams AND charts_diagrams_diagrams_as_long_text
> > IF contains_charts_diagrams AND charts_diagrams_as_non_graphical_data
> 
> Where should we add that?

Adding "contains_charts_diagrams AND" should be part of the 4.6.3 Instructions #1 & #2

**Comment by iherman** [comment]
> > Shouldn't we then define lang="en-US" xml:lang="en-US"?
> 
> @mattgarrish, @iherman ?

You mean in the html element at the top of the file (instead of just 'en')? Yes, strictly speaking, this should be done, because W3C publication rules require US English. I am not sure that we did that systematically in our documents. @mattgarrish ?

**Comment by iherman** [comment]
> > > Shouldn't we then define lang="en-US" xml:lang="en-US"?
> > 
> > 
> > @mattgarrish, @iherman ?
> 
> You mean in the html element at the top of the file (instead of just 'en')? Yes, strictly speaking, this should be done, because W3C publication rules require US English. I am not sure that we did that systematically in our documents. @mattgarrish ?

I just checked our core specifications and yes, it is systematically set. So yes, @gautierchomel, this should be done.

**Comment by gautierchomel** [comment]
> > > IF contains_charts_diagrams AND charts_diagrams_diagrams_as_long_text
> > > IF contains_charts_diagrams AND charts_diagrams_as_non_graphical_data
> Adding "contains_charts_diagrams AND" should be part of the 4.6.3 Instructions 1 & 2

Agree (see proposal in #288
