### ISSUE TITLE
ONIX display - other values - Single logical reading order - code 13

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#299]
In the Display techniques for ONIX document - propose to add the single logical reading order (ONIX code 13 from list 196) to the Supports non visual reading section.

**Comment by chrisONIX** [comment]
CROSSWALK - https://w3c.github.io/a11y-discov-vocab/crosswalk/

Currently schema.org readingOrder is mapped to ONIX code 13 from list 196 Single logical reading order

**Comment by gautierchomel** [comment]
>  propose to add the single logical reading order (ONIX code 13 from list 196) to the Supports non visual reading section

It would add a lot of complexity and mean that this metadata becomes crucial to inform. 

Also, the reading order is a common problem with PDFs, not so much with EPUBs.

Maybe it could be used to inform possible warnings in case of known limited accessibility or add a warning definition to "Additional Accessibility information".
