### ISSUE TITLE
Reference to IDPF, which should be updated

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#30]
I believe the formal reference to specifications has been updated from IDPF to W3C. So, where it says: 
href="http://www.idpf.org/epub/a11y/accessibility-20170105.html#wcag-a" />  should be updated to the current specification.

**Comment by avneeshsingh** [comment]
We should point to member submission: https://www.w3.org/Submission/epub-a11y/

**Comment by gregoriopellegrino** [comment]
I'm looking at it now, not sure if it needs to be updated. The URLs given are those of the metadata examples that point (still) to the IDPF, but ch for the moment we haven't talked about updating.

**Comment by avneeshsingh** [comment]
This is for conformance metadata. 
This will get updated after release of EPUB Accessibility 1.1, because then we will refer to latest revision of EPUB Accessibility, in which this issue is already fixed.
