### ISSUE TITLE
ONIX display - other values - Aria roles

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#301]
In the Display techniques for ONIX document - propose to add the Aria roles provided (ONIX code 30 - from list 196) to the Navigation section

**Comment by chrisONIX** [comment]
Already in https://w3c.github.io/a11y-discov-vocab/crosswalk/ 
schema.org - ARIA

**Comment by gautierchomel** [comment]
This new version of the principle prioritizes features oriented toward non-AT users; this is a good move toward more inclusive and less specialised accessibility. 

Still, there's probably a lot of content made accessible specifically for screen readers and other Assistive Technologies, and this should probably be able to surface somewhere. 

I miss the "Screen readers friendly" wording from the previous version of the guide and feel that would probably be a nice addition, but I'm not sure if it has to go to _Navigation_ or to _Additional Accessibility Information_.
