### ISSUE TITLE
ONIX display - other values - Text-to-speech hinting - code 21

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#302]
In the Display techniques for ONIX document - propose to add the text-to-speech hinting provided (ONIX Code 21 from list 196) to the  Additional accessibility information - clarity section.

**Comment by chrisONIX** [comment]
CROSSWALK - https://w3c.github.io/a11y-discov-vocab/crosswalk/
schema.org ttsMarkup already mapped to ONIX codes 21 - Text-to-speech hinting provided and code 22 - Language tagging provided from list 196

**Comment by gautierchomel** [comment]
Added by #353

**Comment by gregoriopellegrino** [comment]
Fixed, since we have merged
