### ISSUE TITLE
ONIX display - other values - Open captions - code V211

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#305]
In the Display techniques for ONIX document - propose to add the Open captions (ONIX code V211 from list 175) to the Additional accessibility information - Adaptation section OR add a new Multi-media section.

**Comment by chrisONIX** [comment]
CROSSWALK - suggestion 
https://w3c.github.io/a11y-discov-vocab/crosswalk/ 
schema.org - open captions should map to ONIX code V211 from list 175

**Comment by gautierchomel** [comment]
Added by #353

**Comment by gregoriopellegrino** [comment]
Fixed, since we have merged
