### ISSUE TITLE
ONIX display - other values - Sign language  - code V213

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#306]
In the Display techniques for ONIX document - propose to add the Sign language interpretation  (ONIX code V213 from list 175) to the Additional accessibility information - Adaptation section OR add a new Multi-media section.
NB this code is being added to this list in July 2024.

**Comment by gautierchomel** [comment]
Added by #353

**Comment by gregoriopellegrino** [comment]
Fixed, since we have merged
