### ISSUE TITLE
ONIX display - other values - Full transcript - code V212

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#307]
In the Display techniques for ONIX document - propose to add the Full transcript (ONIX code V212 from list 175) to the Additional accessibility information - Adaptation section OR add a new Multi-media section.
NB this code is being added to this list in July 2024.

**Comment by chrisONIX** [comment]
CROSSWALK - https://w3c.github.io/a11y-discov-vocab/crosswalk/
Suggested addition to crosswalk 
schema.org transcript map to ONIX code V212 from list 175 _Full transcript

**Comment by gautierchomel** [comment]
Added by #353

**Comment by gregoriopellegrino** [comment]
Fixed, since we have merged
