### ISSUE TITLE
ONIX display - other values - Dyslexia readability - code 24

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#308]
In the Display techniques for ONIX document - propose to add the Dyslexia readability  (ONIX code 22 from list 196) to the Additional accessibility information - Adaptation section

**Comment by chrisONIX** [comment]
CROSSWALK - https://w3c.github.io/a11y-discov-vocab/crosswalk/

Currently no equivalent in schema.org

**Comment by gautierchomel** [comment]
Added by #353

**Comment by gregoriopellegrino** [comment]
Fixed, since we have merged
