### ISSUE TITLE
ONIX display - other values - Use of color is not sole means of conveying information - code 25

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#309]
In the Display techniques for ONIX document - propose to add Use of color is not sole means of conveying information (ONIX code 25 from list 196) to the to Additional accessibility information - clarity section

**Comment by chrisONIX** [comment]
CROSSWALK _https://w3c.github.io/a11y-discov-vocab/crosswalk/

in schema.org there is colorDependent and the ONIX code 25 from list 196 is the opposite - maybe both need to be in the crosswalk but not as a direct mapping

**Comment by gautierchomel** [comment]
Added by #353

**Comment by gregoriopellegrino** [comment]
Fixed, since we have merged
