### ISSUE TITLE
Small typo in section 3 about link or image

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#31]
In section three a  sentence says: At a very high level when displaying information about an EPUB you may just want to acknowledge that there is “Accessibility Features” or “Accessibility Information” available and if the user would like to get at this information they can click a link or an image which will then provide the information that is discussed below.

I think that click a link or image should more correctly say click a text or image link. Perhaps activate a text or image link is even better.

**Comment by avneeshsingh** [comment]
We should replace with "activate a text or image link"

**Comment by clapierre** [comment]
With all the changes that has happened @GeorgeKerscher can you provide the section in the current document where this occurs. I can't seem to find this reference.
