### ISSUE TITLE
ONIX display - other values - Use of ultra-high contrast between text and background color - code 37

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#311]
In the Display techniques for ONIX document - propose to add the Use of ultra-high contrast between text and background color (ONIX code 37 from list 196) to the Additional accessibility information - Adaptation section

**Comment by chrisONIX** [comment]
CROSSWALK
https://w3c.github.io/a11y-discov-vocab/crosswalk/
highContrastDispalay is already mapped to ONIX code 26 and ONIX code 37 from list 196

**Comment by gautierchomel** [comment]
Added by #353

**Comment by gregoriopellegrino** [comment]
Fixed, since we have merged
