### ISSUE TITLE
ONIX display - other values - Visible page numbering - E205

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#312]
In the Display techniques for ONIX document - propose to add the Visible page numbering (ONIX code E205 from list 175) to the Additional accessibility information - clarity section

**Comment by chrisONIX** [comment]
CROSSWALK - https://w3c.github.io/a11y-discov-vocab/crosswalk/

There is currently no equivalent in schema.org ?

**Comment by gautierchomel** [comment]
Added by #353

**Comment by gregoriopellegrino** [comment]
Fixed, since we have merged
