### ISSUE TITLE
ONIX display - other values - Use of high contrast between foreground and background audio - code 27

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#313]
In the Display techniques for ONIX document - propose to add the Use of high contrast between foreground and background audio (ONIX code 27 from list 196) to the Additional accessibility information - Clarity section

**Comment by chrisONIX** [comment]
CROSSWALK - https://w3c.github.io/a11y-discov-vocab/crosswalk/
highContrastAudio is mapped to ONIX code 27 from list 196

**Comment by gautierchomel** [comment]
Added by #353

**Comment by gregoriopellegrino** [comment]
Fixed, since we have merged
