### ISSUE TITLE
ONIX display - other values -  PDF/ UA - 1 and PDF/ UA- 2 - codes 05 & 06

### ISSUE THREAD

**Issue by chrisONIX** [w3c/publ-a11y#322]
In the Display techniques for ONIX document - propose to add the PDF/ UA 1 and PDF/ UA - 2 (ONIX codes 05 and 06 from code list 196) to either the Conformance section OR add this to the Principals section.

NB code 06 will be added to list 196 in July 2024

**Comment by gautierchomel** [comment]
I am not sure here as it looks like the mapping is not true. 
* An UA compliant PDF is certainly Tagged
* A tagged PDF is not sufficient to be UA compliant

**Comment by chrisONIX** [comment]
Closed as 111  used for this topic
