### ISSUE TITLE
Techniques also reference IDPF URI

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#33]
In the EPUB techniques document, it says:
NOTE
The above three URIs could change in the future since they point to an IDPF page; this work has been moved to the W3C. If a change occurs, other URIs will be recommended.

Should we change these as well?

**Comment by avneeshsingh** [comment]
We are updating these conformance links in EPUB Accessibility 1.1, which will be published in 2022. For now EPUB Accessibility 1.0 is the latest published document, which has IDPF url.
I believe we should not refer to in-progress document. We can update these links as soon as EPUB Accessibility 1.1 reaches CR or rec.

**Comment by mattgarrish** [comment]
Perhaps this could be worded more along these lines:

The above three URLs could change in the future since they reference the IDPF domain. Revisions to the standard are now being conducted in the W3C. When a new version is released, new W3C URLs will be recommended.
