### ISSUE TITLE
A11y metadata for EPUB 3 with media overlays

### ISSUE THREAD

**Issue by llemeurfr** [w3c/publ-a11y#34]
From a recent discussion in the [Thorium Reader issue 1332](https://github.com/edrlab/thorium-reader/issues/1332), it appears that the way to tag EPUB 3 with media overlays is unclear. 

Which metadata (accessMode, accessModeSufficient) and values should an author associate with such an ebook?

**Comment by avneeshsingh** [comment]
Copying the text from techniques.
I think the last line (note) is creating the confusion, we should discuss it in the con call.

This data is derived from the EPUB package metadata inside the Package Document:
EXAMPLE 5
<meta property="schema:accessModeSufficient">auditory</meta>
If this metadata exists (ie. auditory within accessModeSufficient by itself) then report Audiobook: Yes.

Important: This is not the same as textual, auditory or auditory, textual as this indicates that the book requires both textual and auditory abilities to access the data, not auditory alone. Only having accessModeSufficient be auditory as a separate entry ensures the document is an audiobook.

NOTE
As long as you find <meta property="schema:accessModeSufficient">auditory</meta> the book can claim Audiobook: Yes.

**Comment by avneeshsingh** [comment]
After discussion in con call, the term audio book is changed to full audio and audio sync with text publications are also included in this category.
The text in the guide and techniques has been updated accordingly.
