### ISSUE TITLE
Non Visual Reading Unknown exist in principles but not in technic

### ISSUE THREAD

**Issue by gautierchomel** [w3c/publ-a11y#367]
In principles there is a sentence [Not known if readable in read aloud and braille](https://github.com/w3c/publ-a11y/blob/e50ad271f3e41b391d4c62d62b1820bfe4a830e2/UX-Guide-Metadata/draft/principles/index.html#L371) That is not documented in the Technics.

**Comment by GeorgeKerscher** [comment]
Commented out the fourth string in principles. The commit will close this issue once merged.
