### ISSUE TITLE
ONIX tecnics refers to Unknown Audio but this is not present in Principles

### ISSUE THREAD

**Issue by gautierchomel** [w3c/publ-a11y#369]
ONIX technics refers to [No information about pre-recorded audio](https://github.com/w3c/publ-a11y/blob/e50ad271f3e41b391d4c62d62b1820bfe4a830e2/UX-Guide-Metadata/draft/techniques/onix-metadata/index.html#L574) but this example does not exist in the principles.

**Comment by gautierchomel** [comment]
Not sure I understand well, but as it is I feel that millions of textual ebooks would have this mention, which would be confusing.

**Comment by GeorgeKerscher** [comment]
Correct, we do not want to say that no audio is present. I believe this has been corrected in the latest version of the guide.
