### ISSUE TITLE
What should the User Experience guide recommend to be displayed when no accessibility metadata is available

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#38]
Currently the implementations of accessibility metadata do not show anything when no accessibility metadata is available. While this spares the publisher embarrassment, it does not help to promote the need for accessibility metadata. Perhaps we should add something about this in our user experience guide. I suggest this be considered for a second release of the user experience guide.

**Comment by rickj** [comment]
What we are showing when there is no metadata:  "The publisher of this title has not provided any details on the accessibility features that may be included. You should contact them for more information."
