### ISSUE TITLE
Questions about the Display Techniques documents

### ISSUE THREAD

**Issue by rickj** [w3c/publ-a11y#381]
Referencing the Draft Community Group Reports 21 August 2024 for ONIX and for EPUB

- All calculation in the techniques documents use the 'Compact explanations' from the principles document.  Should the techniques documents reference that there are 'Descriptive explanations' also available?  (on this note, there are no unambiguous identifiers for the explanations, and you have to assume that the order presented is the same, and that (as an example) the third one in the list for descriptive is the same as the third one in the list for compact)
- 4.1 Visual adjustments - the wording in item 3 under 4.1.3 Instructions is "Appearance modifiability not known".  The wording of the third item in the 4.1.1 of the principles document is "Ability to modify the appearance is not known".  Which one is to be used?
- 4.2 Supports nonvisual reading - both techniques documents have three possible results in the calculations at 4.2.3 Instructions, however, the principles document has four possible outcomes.  There is no calculation that results in "Not known if readable in read aloud and braille"
- 4.3 Conformance - item 1 under 4.3.3 Instructions results in "This publication exceeds accepted accessibility standards" which is not listed as a statement in the principles document.  The same is true for item 4 "Conformance to accepted standards for accessibility of this publication cannot be determined", and item 9 "This publication claims to meet ...", and item 22 "For more information refer to the certifier's report"
- 4.5 Navigation - the statements in the principles document do not match those in the techniques documents
- 4.6 Charts, diagrams, and formulas - the statements in the principles document do not match those in the techniques documents
- 4.7 Hazards - line 4 in 4.7.3 Instruction referenced the descriptive explanation, rather than the compact one others are using.
- 4.8 Accessibility summary - the "No accessibility summary" calculation in the techniques documents is not mentioned in the principles document

**Comment by clapierre** [comment]
Great observations Rick, we will need to make sure these 3 documents are in harmony.

**Comment by avneeshsingh** [comment]
The topic was discussed in Sept 12, 2024 meeting:

AvneeshSingh: https://github.com/w3c/publ-a11y/issues/381

gpellegrino: I think while working on localization part with IDs and strings, most of those issues will be resolved. We can pause this issue and see how the landscape is later.

AvneeshSingh: I think we should take up the first question, the techniques provide the compact statements, will the techniques also support descriptive statements?

gpellegrino: for each ID there is a compact and a descriptive. implementors can switch.

CharlesL: we may want to state that more explicitly in the techniques.

CharlesL: the principle document shows that, I am not sure we have to multiply examples in the techniques

AvneeshSingh: yes, we should have a note for using compact VS descriptive statements in techniques documents.

AvneeshSingh: Work will follow in editors call.

**Comment by GeorgeKerscher** [comment]
I believe that all items have now been addressed. The hazard compact and descriptive strings are the same.

**Comment by GeorgeKerscher** [comment]
Closing because all the items have been addressed. If something is still missing, please file a new issue.
