### ISSUE TITLE
Metadata guide title

### ISSUE THREAD

**Issue by mattgarrish** [w3c/publ-a11y#403]
It's been noted that the current title is a bit too broad, since we're focused on display for publications.

I think it would help to add "Publication" to the title, but as the title is already quite long maybe we could also look at shortening it to:

> UX Display Guide for Publication Accessibility Metadata 2.0

I expect the audience for this document will already know UX as an acronym so we don't need to write it out in full (an abbr tag could always be added if we think it's important).

**Comment by gautierchomel** [comment]
+1 to abbr tag :)

**Comment by GeorgeKerscher** [comment]
It was mentioned on the editors call, that digital publications should be emphasised. I am thinking that it would only make the title longer to include it there, and we can clarify that for anybody who begins to read.

**Comment by gregoriopellegrino** [comment]
My only doubt is that, especially in the library world, there may be an expectation that the guide will serve to describe accessible print publications (printed Braille, enlarged characters, etc.).

**Comment by mattgarrish** [comment]
> there may be an expectation that the guide will serve to describe accessible print publications

I think that might be something to figure out for the body text. The title isn't specific to digital at the moment.

**Comment by gregoriopellegrino** [comment]
Perhaps the term "UX" is leading us astray and stretching the title?

How about:

> Display Guide for Accessible Digital Publication Metadata 2.0

or

> Display Guide for Digital Publication Metadata 2.0

**Comment by mattgarrish** [comment]
Isn't the case for physical media the same as PDF, though? An ONIX record can describe the accessibility features of a braille or large print book, for example. Is that out of scope?

**Comment by mattgarrish** [comment]
> Perhaps the term "UX" is leading us astray and stretching the title?

This I agree with. I don't know that the guide really goes into the UX aspect since we explicitly stay out of how to present the strings. It only scratches the surface of UX by focusing on making human-readable strings.

**Comment by GeorgeKerscher** [comment]
What about Display Guide for Accessibility Metadata in Digital Publications 2.0

**Comment by mattgarrish** [comment]
> Display Guide for Accessibility Metadata in Digital Publications 2.0

This works for me, with or without digital depending on what's priority.

**Comment by gregoriopellegrino** [comment]
Con una piccola modifica:

> Display Guide for Accessibility Metadata _of_ Digital Publications 2.0

**Comment by mattgarrish** [comment]
Or perhaps even more simply:

> Accessibility Metadata Display Guide for Digital Publications 2.0

**Comment by avneeshsingh** [comment]
Do we need "digital" in the title. I think we do not need to write the title like a legal statement, which covers all aspects. Since "accessibility metadata" is used in the title, it makes it obvious that we are talking in the context of digital space.

**Comment by gregoriopellegrino** [comment]
I am not very sure that this is crystal clear to all stakeholders. For example, in the working group in IFLA there is a lot of talk about metadata to describe accessible physical books (Braille, enlarged characters, augmentative communication, etc.).
