### ISSUE TITLE
Strings present in techniques, missed in principles

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#408]
I have identified these strings (below the IDs) that are present in the techniques, but are missing in the principles:

- conformance-aaa
- unknown-conformance
- conformance-no
- conformance-certifier
- conformance-certifier-credentials
- conformance-wcag-2-2
- conformance-level-aaa
- pre-recorded-audio-no-metadata
- navigation-structural
- navigation-no-metadata
- charts-diagrams-formulas-accessible-chemistry
- hazards-plural
- hazards-singular
- hazards-no-metadata
- accessibility-summary-no-metadata
- tbd
- legal-considerations-no-metadata
- additional-accessibility-information-adaptation-audio-descriptions
- additional-accessibility-information-adaptation-braille
- additional-accessibility-information-adaptation-closed-captions
- additional-accessibility-information-adaptation-open-captions
- additional-accessibility-information-adaptation-tactile_graphic
- additional-accessibility-information-adaptation-tactile_object
- additional-accessibility-information-adaptation-transcript
- additional-accessibility-information-adaptation-sign-language
- additional-accessibility-information-clarity-aria
- additional-accessibility-information-clarity-full-ruby-annotations
- additional-accessibility-information-clarity-text-to-speech-hinting
- additional-accessibility-information-clarity-high-contrast-between-foreground-and-background-audio
- additional-accessibility-information-clarity-high-contrast-between-text-and-background
- additional-accessibility-information-clarity-large-print
- additional-accessibility-information-clarity-page-breaks
- additional-accessibility-information-clarity-ruby-annotations
- charts-diagrams-formulas-non-graphical-data
- additional-accessibility-information-adaptation-dyslexia-readability
- additional-accessibility-information-adaptation-full-transcript
- additional-accessibility-information-clarity-color-not-sole-means-of-conveying-information
- additional-accessibility-information-clarity-ultra-high-contrast-between-text-and-background
- additional-accessibility-information-clarity-visible-page-numbering
- additional-accessibility-information-clarity-without-background-sounds

Probably not all are to be included in the principles...

**Comment by gregoriopellegrino** [comment]
- @GeorgeKerscher: we can add strings for no metadata with a note (pre-recorded-audio-no-metadata, navigation-no-metadata, pre-recorded-audio-no-metadata, navigation-no-metadata, hazards-no-metadata, accessibility-summary-no-metadata)
- @GeorgeKerscher: we should add an example for WCAG 2.2 conformance
- @gregoriopellegrino:  fix in principles conformance-certifier conformance-certifier-credentials
- @GeorgeKerscher: add examples for navigation-structural, charts-diagrams-formulas-accessible-chemistry, charts-diagrams-formulas-non-graphical-data

**Comment by GeorgeKerscher** [comment]
Finishing this issue up.

I added the strings to the issue 266. and also here.

ID:  charts-diagrams-formulas-accessible-chemistry

  Descriptive:  Chemistry is in an accessible format.
  Compact:  "Accessible chemistry content"


I will create another issue with problems I see in this section.

**Comment by GeorgeKerscher** [comment]
I have a question:

We have the suggestion, • @GeorgeKerscher: we can add strings for no metadata with a note (pre-recorde d-audio-no-metadata, navigation-no-metadata, pre-recorded-audio-no-metadata, navigation-no-metadata, hazards-no-metadata, accessibility-summary-no-metadata)

Are we suggesting to say,
NOTE
This key information can be hidden if metadata is missing.

and add Alternatively it can be stated that no (name of feature)  metadata is present.

Is that what we want in the note for each of these sections?

**Comment by gregoriopellegrino** [comment]
I think so...

**Comment by GeorgeKerscher** [comment]
Closing because all the items have been addressed. If something is still missing, please file a new issue.
