### ISSUE TITLE
Problem in Charts, Diagrams, and Formulas section

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#417]
In this section in principles, there are two problems.

First  the ID charts-diagrams-formulas-non-graphical-data is present in ONIX but not in EPUB techniques. I cannot understand  what the description means.

Second, in the compact description, math is not present. This may need to be addressed in the creation of the string as it is being concatinated.

**Comment by gregoriopellegrino** [comment]
The ID `charts-diagrams-formulas-non-graphical-data` refers to the ONIX [code 16 of codelist 196](https://ns.editeur.org/onix/en/196/16): **Visualised data also available as non-graphical data**.

The description is: where data visualisations are provided (eg graphs and charts), the underlying data is also available in non-graphical (usually tabular, textual) form.

**Comment by GeorgeKerscher** [comment]
It seems that the techniques for making these accessible is through extended descriptions. 

If that is true, is it covered elsewhere? Withouth a similar value in EPUB metadata,   I don't know what we sould be proposing.

**Comment by gregoriopellegrino** [comment]
Yes, it is about having extended descriptions or links to external resources where to find the data. Maybe it is a string that we can leave only in the ONIX technique.
