### ISSUE TITLE
Intro to key information section

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#422]
Matt made a comment:
The emphasis on “key” information is a bit confusing when there’s no explanation of what non-key metadata is. It might help to have an introduction to section 4 to explain why you’re only calling this metadata out as key. 

***

In section four we identify three sections that should always be displayed.  The other five sections can optionally be displayed. 

The note says:
NOTE
When the content creator does not provide any accessibility metadata for a publication, the three pieces of key information that should always be present can still be shown (with an indication that the information is missing): Visual adjustments, Supports nonvisual reading, and Conformance.

I agree that we should flesh out an introduction to this section that explains what we were thinking. Let us try to nail down that language in this issue.

**Comment by GeorgeKerscher** [comment]
This intro could replace the note that starts this section.

### Introduction to key accessibility information

When focusing on the accessibility of a digital publication,  three  areas of key information come to mind first.

* People who need to adjust the  visual presentation  want to know if they can enlarge the text, which is essential for low vision users. People with dyslexia  must be able to select the font and adjust the foreground, background, and line length. This represents the largest percentage of the print-disabled population.
*  People who use a screen reader need to know if all the content in the title will be accessible to them. When images have text descriptions (alt text), they are assured that they will be not missing out on  essential information. Blind users will greatly benefit from this information as well as individuals who use the read aloud feature in Reading Systems.
*  People who are selecting materials for public institutions such as libraries or schools, need to know if the content conforms to accepted standards.

This is why these guidelines recommend that three pieces of key information should always be displayed:

1. Visual adjustments
2. Supports nonvisual reading
3. Conformance

The other five areas provide details that are essential for specific types of publications. It is expected that these other areas of essential information will give people the information they need to make an informed choice to read a particular title.

**Comment by gregoriopellegrino** [comment]
I like this enhancement of the introduction, thanks.

**Comment by GeorgeKerscher** [comment]
There is a section that was added and merged.
