### ISSUE TITLE
Add the link to logo in certifierCredential

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#426]
Right now, we have:
The publication was certified by Foo's Accessibility Testing
The certifier's credential is "Enterprise Accessibility Rating."

I think we should have at least in one place the logo of the certifier. I think we had this in version 1.
@clapierre l
@gregoriopellegrino 
If we put it in the techniques, then I will put it in the Principles example.

**Comment by gregoriopellegrino** [comment]
I actually don't know how to put the logo reference in the metadata...

**Comment by clapierre** [comment]
The logo potentially would be linked to in the certifier's credential.  This would be more about the retailer may include the logo if one exists for a specific certification.
