### ISSUE TITLE
Math needs to be more prominent

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#429]
In the section which is now: 4.6Charts, diagrams, and formulas

We make it clear that math is covered, but we should make math more prominent.

I would not assume thateverybody thinks that formulas is math. It is also a more difficult word to translate. In the compact output math is not present. If people were searching for math, they would not get a match. I would suggest math and chemistry to be two words that we use.

While we improve this section, do we want to make a distinction  between LaTex and MathML? We could say math as LaTex or math in MathML?

**Comment by gregoriopellegrino** [comment]
I agree about highlighting the fact that there is math. On using technical terms like LaTex or MathML I have my doubts, I don't know how understandable they are by non-technical people...
