### ISSUE TITLE
Presenting accessibilityFeature, accessibilityHazard, accessMode and accessModeSufficient to users

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/publ-a11y#44]
In the current version of the UX Guide, there are no recommandations regarding the way that the following metadata should be displayed to users:

- accessibilityFeature
- accessibilityHazard
- accessMode
- accessModeSufficient

[The first example in the guide](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/principles/#example-1) simply lists these values "as-is" which doesn't feel like a good approach from a UX perspective as most of these metadata are hard to understand without additional context.

While the guide clearly states that the these metadata are meant to be machine-readable, this can be handled using JSON-LD or microdata easily and doesn't require displaying these same values as-is to users.

Since the guide recommends to implementers that these metadata should be displayed, it should also recommend IMO how they should be displayed. 

For example:

- instead of just displaying `tableOfContents` in Accessibility Features
- we could recommend displaying "This publications contains a table of contents".

The LIA website is a good example for this, as accessibility features are clearly listed in a way that users would understand: https://catalogo.fondazionelia.org/content/later-ediz-italiana-9788892740839

We're in the process of implementing these guidelines in our various products (starting with our portal for library patrons) at De Marque and while the recommandations for the rest of the metadata are clear enough, we're a bit struggling with this remaining set of metadata.

**Comment by HadrienGardeur** [comment]
By the way, for those interested here's what we've implemented so far:

- display if a publication is accessible and allow the user to filter publications based on that
- display if a publication is screen reader friendly and allow the user to filter publications based on that
- display if a publication is full audio and allow the user to filter publications based on that
- show what the publication conforms to while browsing (click to display a modal) or on a publication's page

The screenshot are in French, but they should be fairly easy to understand.

![Accessibility info while browsing](https://user-images.githubusercontent.com/90989/115377146-a268a000-a1cf-11eb-8ca1-656552d3230d.png)
![Modal for detailed accessibility info while browsing](https://user-images.githubusercontent.com/90989/115377209-b0b6bc00-a1cf-11eb-83b5-0e8f8c9a976b.png)

**Comment by clapierre** [comment]
@HadrienGardeur there are detailed examples in the [Schema techniques documents](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/techniques/epub-metadata.html) on how this metadata should look.
I like what you are doing though and maybe we can enhance our techniques document.

**Comment by HadrienGardeur** [comment]
There are a few examples (mostly in https://w3c.github.io/publ-a11y/UX-Guide-Metadata/techniques/epub-metadata.html#ui-26) but nothing exhaustive.

For `accessMode` and `accessModeSufficient`, I don't think that our current examples are really understandable for users/patrons. Looking at https://schema.org/accessMode, what they have in their JSON-LD examples is potentially more interesting:
```
"accessModeSufficient": [
    {
      "@type": "ItemList",
      "itemListElement": ["textual"],
      "description": "See the text"
    },
    {
      "@type": "ItemList",
      "itemListElement": ["textual", "visual"],
      "description": "See the text and images"
    },
    {
      "@type": "ItemList",
      "itemListElement": ["auditory"],
      "description": "Hear the text and image descriptions"
    },
    {
      "@type": "ItemList",
      "itemListElement": ["auditory", "visual"],
      "description": "Hear the text and see the images"
    },
    {
      "@type": "ItemList",
      "itemListElement": ["auditory", "visual", "textual"],
      "description": "Hear the text and see the text and images"
    }
  ]
  ```

**Comment by HadrienGardeur** [comment]
@clapierre on a related note, is there any regular call for the group working on this document? I'm getting lost with all the TFs across both WG/CG, it's frankly getting difficult to keep track of who's doing what.

**Comment by avneeshsingh** [comment]
+1 @clapierre , we can improve the techniques document for this. Techniques document can be updated more frequently than the principles document. So, we can plan to make this change in next revision.

@HadrienGardeur, right now we do not have regular calls of accessibility task force of CG. Most of the work is going on issue tracker. We schedule a call whenever it  is required.
The work on accessibility metadata is progressing in publishing community group.
And the work on EPUB accessibility and related accessibility improvements is progressing in EPUB 3 WG. Accessibility task force of EPUB 3 WG regularly meets on 2nd and 4th Thursday of the month.

**Comment by HadrienGardeur** [comment]
NNELS has also rolled out their support for displaying accessibility features:

- example: https://nnels.ca/items/amazing-black-atlantic-canadians-inspiring-stories-courage-and-achievement
- list of features: https://nnels.ca/understanding-accessibility-features

Their approach is a bit different from the W3C recommandation since accessibility features are listed directly instead of a higher-level concept like "Screen-reader friendly".

If I map their list back to schema.org:

| schema.org term | English equivalent |
| ----------------- | ------------------ |
| displayTransformability | Customizable display |
| alternativeText | Described images |
| describedMath | Described math |
| structuralNavigation | Heading navigation |
| printPageNumbers | Print page numbers |
| synchronizedAudioText | Read aloud |
| tableOfContents | Table of contents navigation |
| none | None provided |

**Comment by danielweck** [comment]
Hello all, there is a typo in the document, singular vs. plural `accessibilityHazard(s)`:
https://github.com/w3c/publ-a11y/blob/fcff9ce90cf5977446b4608ad9611f05bd9bb72e/UX-Guide-Metadata/draft/techniques/epub-metadata/index.html#L807-L809
