### ISSUE TITLE
Version of first release of user experience guide for displaying accessibility metadata

### ISSUE THREAD

**Issue by avneeshsingh** [w3c/publ-a11y#45]
We are in last stages of first release of user experience guide for accessibility metadata along with techniques for ONIX and EPUB+schema.org accessibility metadata.
What should be the version for this first release.
Should we use version 1.0?

https://w3c.github.io/publ-a11y/UX-Guide-Metadata/principles/

**Comment by GeorgeKerscher** [comment]
I think version 1.0 is just fine.

**Comment by gregoriopellegrino** [comment]
Me too
