### ISSUE TITLE
Add "libraries" to General Overview

### ISSUE THREAD

**Issue by spudthebud** [w3c/publ-a11y#465]
I'm commenting on "Accessibility Metadata Display Guide for Digital Publications 2.0"

I'm commenting on the [General Overview](https://w3c.github.io/publ-a11y/a11y-meta-display-guide/2.0/guidelines/#general-overview) section
>  This document targets implementers such as bookstores, retailers, distributors etc.

I suggest adding libraries.

**Comment by avneeshsingh** [comment]
These guidelines are useful for libraries. So, this looks appropriate.
A topic for next editors' call.

**Comment by GeorgeKerscher** [comment]
I think this is an easy decision. I was just going to add it.
