### ISSUE TITLE
Hard to understand navigation information

### ISSUE THREAD

**Issue by gautierchomel** [w3c/publ-a11y#469]
The second draft of the display guide adds to the Navigation section the example 
_"Contains book elements such as headings, tables, etc for structured navigation"_ 
Which is specialised wording that is hard to understand for anyone outside of technical experts. 

If we are to keep this information, it could be made more understandable like _"This ebook includes structure elements for headings and tables to help you navigate easily"_.

But I also think that this is mainly useful for AT users, so we could explicitly mention it with something like _"This ebook includes structure elements for headings and tables to help assistive technologies users navigate easily."_

(I resist the temptation to propose the reintroduction of "screen reader friendly")

**Comment by gautierchomel** [comment]
If we are to keep this information, it could be made more understandable like "This ebook includes features like headings and tables to help you navigate easily".

But I also think that this is of use for AT users mainly, so we could explicitly mention it with something like "This ebook includes features like headings and tables to help assistive technologies users navigate easily".

(I resist the temptation to propose the reintroduction of "screen reader friendly")

**Comment by gautierchomel** [comment]
Markup, Structure, and Elements are all technical terms. What about:

_Facilitates assistive technologies shortcut navigation_

**Comment by GeorgeKerscher** [comment]
Reworked the navigation section. If not resolved, open a new issue with specific recommendations.
