### ISSUE TITLE
Vocabulary localisation difficulties: Meaning of Certification

### ISSUE THREAD

**Issue by gautierchomel** [w3c/publ-a11y#472]
This issue is for documentation purposes about the different meanings of the word "Certification" in different geographies. 

During our discussions, we encountered difficulties to find a common understanding to the word “Certification” and its implications. In France, a dedicated workgroup studied this in the context of implementing the European Accessibility Act. It concluded that Certification is attached to a legally registered process providing a described scheme.  

An example is the Qualiopi certification, which certifies training centers. It’s defined by Article 6 of Law no. 2018-771 of September 5, 2018, based on a single national reference system. The Certifier is accredited and registered by the state, and the certification framework was developed in collaboration with a majority of representative vocational training players under the guidance of the French Ministry of Labor's Directorate General for Employment and Vocational Training (DGEFP). 

Alternatively, we found that (in the french context) certification can be provided through participative systems recognition, i.e. a collectively agreed framework which seems to me the nearest of what we actually mean by Certification, WCAG techniques being the framework. Alas, previous examples shows needs to be more precise than WCAG techniques (French [RGAA](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/) details test methodology for each criteria to ensure that two evaluators find the same result). 

Therefore, translating “Certification” in French is tricky and necessitates specifying its non-legal aspect, like “Non-Legally Binding” or “Private”. We could alternatively use “Attestation” or “Conformity endorsement” but the consumer understanding may be affected. Looking for different vocabularies, we found that [EPUB Accessibility 1.1 section 3.5 Conformance reporting](https://www.w3.org/TR/epub-a11y-11/#sec-conf-reporting)  uses the words “Evaluator” and “Evaluation”.

**Comment by GeorgeKerscher** [comment]
I believe we have addressed these issues. If there is still a problem, please file a new issue with specific comments.
