### ISSUE TITLE
Identification of audio-only books in EPUB techniques

### ISSUE THREAD

**Issue by jonaslil** [w3c/publ-a11y#480]
In [4.4.3 Instructions](https://w3c.github.io/publ-a11y/a11y-meta-display-guide/2.0/draft/techniques/epub-metadata/index.html#pre-recorded-audio), step 2 checks for the presence of `accessModeSufficient` value `"auditory"`. If present, it displays "Audio only" (compact explanation).

However, `accessModeSufficient` `"auditory"` can also appear in books with synchronized text and audio. In such cases, `accessModeSufficient` `"textual"` should also be included. See [EPUB Accessibility Techniques 1.1, 3.3](https://www.w3.org/TR/epub-a11y-tech-11/#accessMode-sync).

So `accessModeSufficient` `"auditory"` alone does not confirm a book is audio-only. To determine this, it seems necessary to also check for the absence of `accessMode` `"textual"`, `accessModeSufficient` `"textual"`, or other indications of text content.

The ONIX logic addresses this with the condition `AND NOT synchronised_pre_recorded_audio`, ensuring synchronized text and audio books are not misclassified.

**Comment by GeorgeKerscher** [comment]
The Prerecorded audio section has been revised and should address the issues. Will close the issue. If not resolved, please file a new issue.
