### ISSUE TITLE
Supports nonvisual reading

### ISSUE THREAD

**Issue by jonaslil** [w3c/publ-a11y#483]
I propose updating this heading, both in the documents and when publication metadata is displayed, to:

"Support for nonvisual reading"

This phrasing aligns better with the other headings, which are noun phrases describing a topic rather than claims about accessibility.

The current heading, "Supports nonvisual reading," can be misinterpreted as a statement about the publication's accessibility. In fact, this phrasing is used in 5.1 to describe a filtering option for publications that meet the requirements for nonvisual reading. However, having this heading followed by "Not fully readable in read aloud or dynamic braille" creates an inconsistency and may cause confusion.

**Comment by GeorgeKerscher** [comment]
This is a subtle, but important change. It will have an impact in many places. I think we should address this sooner rather than later. I will make the changes in the guidelines and make a PR.
