### ISSUE TITLE
bad image link

### ISSUE THREAD

**Issue by rickj** [w3c/publ-a11y#487]
In the public draft 2 release of the Guidelines the image at https://w3c.github.io/publ-a11y/a11y-meta-display-guide/2.0/guidelines/#processing-guide does not load

**Comment by mattgarrish** [comment]
Yes, it needed to be copied into the release directory. I've fixed this in https://github.com/w3c/publ-a11y/commit/424e431a3040669b6f9207df7c97aa2cc801a98e
