### ISSUE TITLE
Difficulty understanding the prerecorded audio compact descriptions

### ISSUE THREAD

**Issue by mattgarrish** [w3c/publ-a11y#528]
This is the output I got from the algorithm for an audiobook:

```
Prerecorded audio
Audio only
```

It took me some time going from the techniques back to the guidelines and finally to the descriptive statements to discover this is the same as:

```
Prerecorded audio
Audiobook with no text alternative
```

The compact is so compact in this instance I don't know that it will be understandable.

Another output is :

```
Prerecorded audio
Complementary audio and text
```

In this case, the more descriptive statement doesn't help: "Contents available as complementary audio and text"

What is complementary audio and text? Is the point here just that there is audio content in the book?

We need to be careful that the compact statements aren't too compact and that the language is as clear as possible. Users aren't going to have the benefit of the supporting documents.

**Comment by GeorgeKerscher** [comment]
Perhaps we should start from what people expect from the output and make sure the metadata interpretation  is aligned.

I think of:
An audio book without much in the way of navigation. This is most common.
An audio book with some supplementary files, which I do not think are used very much.
A audio book with navigation, the normal DAISY 2.02 or a DAISY 3 title.
A media overlay title, mostly childrens books with fixed layout and audio.
A full text and full audio title in DAISY or with media overlays, which are rare.

A title with a little bit of audio for poetry readings etc. should not be in this list of audio books and is covered in rich media.

Thoughts?

**Comment by mattgarrish** [comment]
> A title with a little bit of audio for poetry readings etc. should not be in this list of audio books and is covered in rich media.

Yes, if this is what complementary audio and text is referring to (i.e., embedded audio content has text equivalents), it seems duplicative with the updated rich content section.

**Comment by mattgarrish** [comment]
If embedded audio is removed, couldn't this category be renamed "Audio playback" and prerecorded put in the descriptions.

For example, the compact string could be one of:

- Prerecorded audio only.
- Prerecorded audio synchronized with text.
- Prerecorded audio not provided.
