### ISSUE TITLE
Guidelines has inconsistent headings before examples

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#532]
Most do not have headings. Navigation has headings before the examples.
rich content has headings before the examples 
additional information has headings. 
What should we suggest? It seems odd to have a heading if there is only one statement.

**Comment by gregoriopellegrino** [comment]
I think this issue is resolved, now I will proceed with aligning the techniques

**Comment by GeorgeKerscher** [comment]
Removed the headings in Rich content, navigation, and additional information.
