### ISSUE TITLE
Rich content requires a close look at variables and strings

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#537]
In the PR 536, the problem of Rich Content and the logic was mentioned. I did not want that to get lost once merged, so creating an issue.

Rich content has many items including math, chemical formulas, vidio prerecorded audio and as a group, charts diagrams, figures, and graphs.

I think our logic now takes all the assigned variables and if they all are missing accessible content, then we report one statement about this not identified as being accessible. 

I think it is more difficult than that! Should we be reporting on each individual item? For example, if math is identified as being present, and if one of the three accessible alternatives, MathML, LaTex, descriped math, are not present then we report that math is not identified as being accessible?

I think that for items that do not have a value of being present, perhaps the presence of audio for a poem or something like that, then it does not belong in this area.

**Comment by clapierre** [comment]
George how would math be identified as being present if it is not in the acessibilityFeatures as MathML, Latex, or describedMath.  It's not like we are going into the EPUB to look for images of math equations, so I am a little confused here.

**Comment by GeorgeKerscher** [comment]
George, Gregorio, and Charles whent through the Rich Content section and came to conclusions.
