### ISSUE TITLE
Alt Text Improvement for Example 1 in Principles document

### ISSUE THREAD

**Issue by clapierre** [w3c/publ-a11y#54]
Example 1
  
The alt text description needs to be improved for the "Toggle box with all accessibility information"
That is a very general description of the image, but the image also has some accessibility features, hazards and access modes before just having …
  
I would recommend:
  
"Toggle box with all accessibility information. Showing: Accessibility Features: alternativeText, longDescriptions, printPageNumbers. Accessibility Hazards: none. AccessMode: visual, textual. …"

**Comment by GeorgeKerscher** [comment]
Revision of the guidelines resolves this problem. If you think there is still a problem, please submit a new issue.
