### ISSUE TITLE
Index for techniques

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#6]
I suggest to:
- remove https://w3c.github.io/publ-a11y/UX-Guide-Metadata/techniques/
- create a super simple page like: https://w3c.github.io/publ-a11y/UX-Guide-Metadata/

**Comment by avneeshsingh** [comment]
For metadata documents, recommendation of the group is to follow the layout of CG report used for EPUB 3
https://www.w3.org/publishing/epub3/

**Comment by gregoriopellegrino** [comment]
If it is ok for everybody, I can do it.

Gregorio
