### ISSUE TITLE
What happens if more than one metadata of the same type is found?

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#61]
A few questions have arisen:
- if there are two _conformsTo_ in an EPUB, what should the platform show? (similarly it can happen for ONIX)
- if there are two _accessibilitySummary_ (in different languages)?
- etc.

I think we have to take into account that for each metadata with cardinality 1 there could be more than one occurrence (not necessarily wrong) and tell the platforms how to behave.

**Comment by gautierchomel** [comment]
Related to #189 and #191
