### ISSUE TITLE
Questions on Certifier Report

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#7]
By George Kerscher (via email)

With the Certifier Report, would this apply if it was self certified? Also, is this always a link to the actual report?

On wiki page: https://github.com/w3c/publ-a11y/wiki/Definitions-and-rationales-for-Accessibility-Metadata

**Comment by gregoriopellegrino** [comment]
My opinion is:
* the Certifier Report doesn't make sense for auto-certified files, but we don't have a programmatic way to say when the file is auto-certified and when there is a third-party certifier instead
* it is always a URL, so it is an active link (I can specify it better in the text)

**Comment by GeorgeKerscher** [comment]
I think you mean self-certification instead of auto. Auto reporting seems like it could get confused with Ace type checking.
