### ISSUE TITLE
full audio versus synthetic speech

### ISSUE THREAD

**Issue by statped** [w3c/publ-a11y#78]
My name is Miriam Hlavaty and I work in Statped. We have been testing a lot of the educational books made by publishers in Norway to see how well suited they are for students with special needs (sight impared, low vision, dyslexia).
Regarding the point 4.2 Full Audio (this question concerns educational books.) In our country several publishers provide books where some of the content has been recorded and is accessible as audio files (in addition to the written text). Basically it is the main body text that has been recorded and exercises, examples in the sidebars etc is not recorded. How should publications like this be marked in their meta data?
Another question: a lot of the same books  also contains a built-in synthetic speech that can be used to access some of the other texts.  Generally this does not work to well as the speech synthesis is unable to render correctly a lot of the special signs used in for instance science books, but the publication still has recorded audio and the possibility for text-to-speech. Is there a standard for how to mark books with built-in text-to-speech technology? It should be added that in some of these books the built-in synthetic speech technology can only be accessed by marking or highlighting the text you want to have read out load so it is not particularly accessible for users with low vision or motor skills issues.

**Comment by GeorgeKerscher** [comment]
There have been many advancements over the past few years to address the problems identified in this issue. I will explain the current state.

Read aloud is the term when a reading systems has a features that takes the text and sends to an engine for speaking the information. This is now quite common. Advances in MathML over the past years makes it now possible for these Read aloud functions to properly present math and chemistry equations in speech and in braille. These engines are using MathAT or MathJax for this conversion.

Sometimes publishers are providing audio files to complement the text. Forexample, a recording of a poem being read. This is marked up in metadata as complementary audio. This is different from an audio book or a book with full audio synchronized with text.

In Accessibility Metadata Display Guide for Digital Publications 2.0, this has been made much more clear.

I am going to close this issue. If you still have questions, please open a new issue with specific questions.
