### ISSUE TITLE
techniques for schema.org a11y metadata also has DC and EPUB vocabulary

### ISSUE THREAD

**Issue by avneeshsingh** [w3c/publ-a11y#8]
The techniques for schema.org accessibility metadata (1.) also has double core and EPUB metadata vocabulary. Therefore it may not be named as schema.org metadata techniques.
1.
https://w3c.github.io/publ-a11y/UX-Guide-Metadata/techniques/schema-org.html

**Comment by avneeshsingh** [comment]
Decision made on February 14, 2020 meeting:
Use the naming pattern like
* Techniques for the display of schema.org and (others) accessibility metadata
* Techniques for the display of ONIX accessibility metadata

Let us finalize the exact names in this thread.

**Comment by GeorgeKerscher** [comment]
the metadata is primarily Schema.org, but there is DCTerms and EPUB defined A11Y, These are close related so I propose:
• Techniques for the display of schema.org and (related) accessibility metadata
• Techniques for the display of ONIX accessibility metadata

**Comment by mattgarrish** [comment]
"schema.org and related" sounds like a mouthful, especially when the relation is the EPUB accessibility specification. Couldn't this just be "Techniques for the display of EPUB accessibility metadata"?

The ONIX metadata is distinct in that it isn't exclusive to distributing EPUBs, and doesn't cover all the same information.

**Comment by mattgarrish** [comment]
But I was going to add that having a single techniques document might make sense if the display is the same and only the source of the information changes. Maintaining two or three documents that all say the same things is asking for trouble.

We could use the details element, for example, to collapse the examples so readers only have to review what they're interested in.

**Comment by GeorgeKerscher** [comment]
I totally agree with Matt. Following on Matt's suggestion to use the details and summary element, we could list each of the entries from the principles document along with a link to that spot in the principals document, and under that item, we could list a details element with Schema, and another details for ONIX. In the future we can add another details element for MARCC. 

This approach would make it easy to find the information one needs.

**Comment by gregoriopellegrino** [comment]
Ok, for me.

Just to remember: the initial idea was to being able to update the docs separately when source specs updates (ONIX usually has two release per year), so as to keep separate versioning for the different techniques.

**Comment by avneeshsingh** [comment]
Another reason highlighted on Feb 14 call was that the reader who is interested in ONIX would not like to go through complexity of schema.org. Similarly one from library community may like to see mainly MARC. And all of these techniques documents would be updated separately at different frequency.

Moving techniques to single document is more of a structural change. We should get inputs from other members of group about it.

**Comment by clapierre** [comment]
Not sure this is possible with W3C respec but we could add some javaScript and at the beginning of the page where one could select either to have automatically opened all the EPUB internal Metadata, ONIX, or MARC etc.  this way one document could be used and the user would still get the desired outcome where the metadata they are interested in would automatically be opened.  The other metadata would be in separate closed details which they could always open manually to view if they so choose.

**Comment by clapierre** [comment]
> Ok, for me.
> 
> Just to remember: the initial idea was to being able to update the docs separately when source specs updates (ONIX usually has two release per year), so as to keep separate versioning for the different techniques.

@gregoriopellegrino we might be able to still have these as separate files which gets pulled into a single document, but if we want everything intermixed for each metadata that would mean six to eight files for each metadata scheme.

E.g.
schema-accessessibilityFeatures
ONIX-accessibilityFeatures
MARC-accessibilityFeatures
schema-accessessibilityHazards
ONIX-accessibilityHazards
MARC-accessibilityHazards
etc.

Then One main document
which includes each of these separate files inside a Summary/Details element

**Comment by gregoriopellegrino** [comment]
I'm sorry, I don't quite understand

**Comment by mattgarrish** [comment]
> so as to keep separate versioning for the different techniques

Are the techniques different, or is it just that the metadata you get the information from might be different? From what was said on the last call, this document is about how to display the metadata, not specifically about how you add it to documents. With some variation because there isn't perfect overlap, it sounds like the display techniques are always the same.

Separate documents isn't the only approach to solving this problem, though. You could simply have a preliminary section that identifies which version of each metadata format the document is current to.

> Not sure this is possible with W3C respec but we could add some javaScript and at the beginning of the page where one could select either to have automatically opened all the EPUB internal Metadata, ONIX, or MARC etc.

Right, respec won't do it for us, but we can always write in our own code to do this, yes.

> Then One main document which includes each of these separate files inside a Summary/Details element

You can do file includes in respec if you want to put each metadata example in a separate file prior to publishing. It tends to come down to personal preference about whether it's easier to edit one document or not. When you chunk at the element level like this, you often lose code complete, validation, etc. in editors.

**Comment by avneeshsingh** [comment]
The consensus in our last call was to keep the structure of document as it is i.e. one document for principles and separate documents for techniques.

**Comment by avneeshsingh** [comment]
Regarding the name of schema.org techniques + double core + EPUB metadata vocabulary document, the suggestion that received good amount of votes in the last call is "EPUB Accessibility Metadata"

Please comment if anyone in the group has a better suggestion, else we can finalize this name for the techniques document.

**Comment by gregoriopellegrino** [comment]
Done, now the title page is a little bit redundant, but coherent: "EPUB Accessibility Metadata Techniques for Displaying Accessibility Metadata for EPUB" 😄
