### ISSUE TITLE
Implementation in French (EDRLab)

### ISSUE THREAD

**Issue by editadapt** [w3c/publ-a11y#80]
Hi everyone, 
We open a project under EDRLab flag to implement the guide in a french context. We plan to :
- translate the guides (in progress)
- build an example page in french (in progress)
- get users and distributors feedback thru working groups
- synthesize, resume and give a feedback here.
This message is to give context about the next issues i'll be opening.

**Comment by gautierchomel** [comment]
The implementation was done and a feedback letter was send to the authors. Detailed Informations and protorypes of the project are available in English in the dedicated [project web page](https://edition-accessible.github.io/signalement/en/index-en.html).
