### ISSUE TITLE
Accessibility of index links to notes

### ISSUE THREAD

**Issue by apgrover** [w3c/publ-a11y#91]
We are considering treatment for index links to notes. For example:
- An index reference to 15n may include an index term in a footnote on page 15.
- An index reference to 315n27 may include an index term in endnote 27 on page 315 (in the endnotes section).

From an accessibility point of view, we are not sure if it is more accessible to link to 
- The page break span (`<span epub:type="pagebreak" role="doc-pagebreak" id="page_15" title="15" />`)
- The note section (if there are multiple notes at the end of a chapter)
- The note itself

For footnotes, linking to the page anchor may give the additional context required to understand the footnote, while for endnotes it may be more effective to link straight to the note. However, we could argue that it is more accurate to always link directly to the note.

For context, we link our index page numbers to the top of the print page because that is what is currently possible in our workflow.

Any thoughts on this?

**Comment by clapierre** [comment]
> `The page break span (<span epub:type="pagebreak" role="doc-pagebreak" id="page_15" title="15" />)`

It is not recommended to use title here as that is not well supported with assistive technologies.  It is recommended to use aria-label.

**Comment by apgrover** [comment]
Thanks for everyone's input! I think this is a helpful direction to consider.

@clapierre in testing we noticed that aria-label on page anchors interrupts the content to announce the page number, and we weren't sure if this was too intrusive. Since it's read aloud, would you recommend adding the word "page" (ex. `aria-label="page 24"`)?

**Comment by GeorgeKerscher** [comment]
I would think it is best to link directly to the item on the page but linking to the page break is quite common. I would just be consistent for the publication you are in. It would be confusing to switch between linking to a paragraph and another link to the page break. Many times, a footnote or an extended description would have a back link to the item referencing the footnote or endnote. I do not think you would have a backlink to the index.

**Comment by clapierre** [comment]
> n testing we noticed that aria-label on page anchors interrupts the content to announce the page number, and we weren't sure if this was too intrusive. Since it's read aloud, would you recommend adding the word "page" (ex. aria-label="page 24")?

Our recommendation has been to include the following text for labels of page #'s " Page xx. "
Note there are spaces at the beginning and end of the label as well as a period after the page number.  The reason being we want to make sure that the text is not concatenated with other surrounding text and we want to have a pause for the screen reader hence the period.

Note this recommendation may change as improvements are made to AT/Reading systems on how this information is exposed.

**Comment by apgrover** [comment]
@GeorgeKerscher Thanks for your thoughts on this. The idea of consistency per document is a very helpful reminder for framing this and other decisions, though here there is a theme of linking directly to the item. We will face this when we address index links to images as well.

@clapierre Thanks for clarifying the page number recommendation. It's at least nice to know the ideal, even when AT/reading systems shift in the future.

**Comment by apgrover** [comment]
I think we're satisfied with the feedback we received on this. Thanks!
